import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.115.0";

import { resolveGradingSport, isFootballGradingSport, isMlbGradingSport } from "../place-test-wager/sport-keys.ts";

const headers={'Content-Type':'application/json'};

const STANDARD_MARKETS=new Set(['h2h','spreads','totals']);
const FOOTBALL_PROP_BASE=new Set(['player_pass_yds','player_pass_tds','player_pass_attempts','player_pass_completions','player_pass_interceptions','player_rush_yds','player_rush_attempts','player_reception_yds','player_receptions','player_rush_reception_yds']);
const MLB_PROPS=new Set(['batter_doubles_alternate','batter_hits','batter_hits_alternate','batter_hits_runs_rbis_alternate','batter_home_runs','batter_rbis','batter_rbis_alternate','batter_runs_scored_alternate','batter_total_bases','batter_total_bases_alternate','pitcher_outs','pitcher_strikeouts_alternate']);
function reply(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers})}
function clean(v:unknown){return String(v??'').trim()}
function norm(v:unknown){return clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null}
function decimalFromAmerican(odds:number){return odds>0?1+odds/100:1+100/Math.abs(odds)}
function isSoccer(sport:string){return ['mls','epl','ucl'].includes(sport)||sport.startsWith('soccer_')}
function propBase(key:string){return key.endsWith('_alternate')?key.slice(0,-10):key}
function isFootballProp(key:string,sport:string){return isFootballGradingSport(sport)&&FOOTBALL_PROP_BASE.has(propBase(key))}
function isMlbProp(key:string,sport:string){return isMlbGradingSport(sport)&&MLB_PROPS.has(key)}
function isoDateAt(value:string,offset=0){const d=new Date(value);d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)}
async function fetchScores(providerSport:string,apiKey:string){const params=new URLSearchParams({apiKey,daysFrom:'3',dateFormat:'iso'});const r=await fetch(`https://api.the-odds-api.com/v4/sports/${encodeURIComponent(providerSport)}/scores/?${params}`);const raw=await r.text();let data:any=[];try{data=raw?JSON.parse(raw):[]}catch{data=[]}if(!r.ok)throw new Error(data?.message||`Scores request failed for ${providerSport}`);return Array.isArray(data)?data:[]}
function scoreForTeam(game:any,teamName:string){const target=norm(teamName);const row=(game?.scores??[]).find((s:any)=>norm(s?.name)===target);return num(row?.score)}
function finalScores(game:any){const homeName=clean(game?.home_team),awayName=clean(game?.away_team);return{home:scoreForTeam(game,homeName),away:scoreForTeam(game,awayName)}}
function gradeStandard(s:any,game:any){if(!game?.completed)return null;const homeName=clean(game?.home_team),awayName=clean(game?.away_team),{home,away}=finalScores(game);if(home===null||away===null)return null;const market=clean(s?.market_key),selection=norm(s?.selection_name),sport=clean(s?.sport_key).toLowerCase(),point=s?.point===null||s?.point===undefined||s?.point===''?null:Number(s.point);let result:'won'|'lost'|'void'|null=null;if(market==='h2h'){const hk=norm(homeName),ak=norm(awayName);if(selection==='draw'||selection==='tie')result=home===away?'won':'lost';else if(selection===hk){if(home>away)result='won';else if(home<away)result='lost';else result=isSoccer(sport)?'lost':'void'}else if(selection===ak){if(away>home)result='won';else if(away<home)result='lost';else result=isSoccer(sport)?'lost':'void'}else return null}else if(market==='spreads'){if(point===null||!Number.isFinite(point))return null;const hk=norm(homeName),ak=norm(awayName);let adjusted:number,opponent:number;if(selection===hk){adjusted=home+point;opponent=away}else if(selection===ak){adjusted=away+point;opponent=home}else return null;result=adjusted>opponent?'won':adjusted<opponent?'lost':'void'}else if(market==='totals'){if(point===null||!Number.isFinite(point))return null;const total=home+away;if(total===point)result='void';else if(selection==='over')result=total>point?'won':'lost';else if(selection==='under')result=total<point?'won':'lost';else return null}else return null;return{selection_id:String(s.id),result,final_home_score:home,final_away_score:away}}
function gradeThreshold(s:any,actual:number,game:any){const point=num(s?.point),side=norm(s?.selection_name);if(point===null||!['over','under'].includes(side))return null;let result:'won'|'lost'|'void';if(actual===point)result='void';else if(side==='over')result=actual>point?'won':'lost';else result=actual<point?'won':'lost';const{home,away}=finalScores(game);return{selection_id:String(s.id),result,final_home_score:home,final_away_score:away}}

async function apiSportsGamesForDate(key:string,date:string){const r=await fetch(`https://v1.american-football.api-sports.io/games?date=${date}`,{headers:{'x-apisports-key':key}});const raw=await r.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(`API-SPORTS games ${r.status}`);return Array.isArray(data?.response)?data.response:[]}
function apiGameTeams(g:any){return{home:clean(g?.teams?.home?.name??g?.home?.name),away:clean(g?.teams?.away?.name??g?.away?.name)}}
function apiGameStatus(g:any){return clean(g?.game?.status?.short??g?.status?.short)}
async function matchApiFootballGame(event:any,key:string,gameCache:Map<string,any[]>){const kickoff=String(event.commence_time);for(const off of [0,-1,1]){const date=isoDateAt(kickoff,off);if(!gameCache.has(date))gameCache.set(date,await apiSportsGamesForDate(key,date));for(const g of gameCache.get(date)??[]){const t=apiGameTeams(g);if(norm(t.home)===norm(event.home_team)&&norm(t.away)===norm(event.away_team))return g}}return null}
async function fetchFootballPlayerStats(gameId:string,key:string,cache:Map<string,any[]>){if(cache.has(gameId))return cache.get(gameId)!;const r=await fetch(`https://v1.american-football.api-sports.io/games/statistics/players?id=${encodeURIComponent(gameId)}`,{headers:{'x-apisports-key':key}});const raw=await r.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(`API-SPORTS player stats ${r.status}`);const rows=Array.isArray(data?.response)?data.response:[];cache.set(gameId,rows);return rows}
function playerStatRows(rows:any[],playerName:string){const target=norm(playerName),found:any[]=[];for(const team of rows)for(const group of team?.groups??[])for(const p of group?.players??[])if(norm(p?.player?.name)===target)found.push({group:clean(group?.name).toLowerCase(),stats:p?.statistics??[]});return found}
function statValue(stats:any[],name:string){const row=stats.find((x:any)=>clean(x?.name).toLowerCase()===name.toLowerCase());return num(row?.value)}
function compAtt(stats:any[]){const row=stats.find((x:any)=>clean(x?.name).toLowerCase()==='comp att');const m=clean(row?.value).match(/^(\d+)\s*\/\s*(\d+)$/);return m?{completions:Number(m[1]),attempts:Number(m[2])}:null}
function footballPropActual(key:string,rows:any[],player:string){const base=propBase(key),pr=playerStatRows(rows,player);if(!pr.length)return null;const group=(name:string)=>pr.find(x=>x.group===name.toLowerCase())?.stats??null;const passing=group('passing'),rushing=group('rushing'),receiving=group('receiving');if(base==='player_pass_yds')return passing?statValue(passing,'yards'):null;if(base==='player_pass_tds')return passing?statValue(passing,'passing touch downs'):null;if(base==='player_pass_interceptions')return passing?statValue(passing,'interceptions'):null;if(base==='player_pass_attempts'){const ca=passing?compAtt(passing):null;return ca?.attempts??null}if(base==='player_pass_completions'){const ca=passing?compAtt(passing):null;return ca?.completions??null}if(base==='player_rush_yds')return rushing?statValue(rushing,'yards'):null;if(base==='player_rush_attempts')return rushing?statValue(rushing,'total rushes'):null;if(base==='player_reception_yds')return receiving?statValue(receiving,'yards'):null;if(base==='player_receptions')return receiving?statValue(receiving,'total receptions'):null;if(base==='player_rush_reception_yds'){if(!rushing&&!receiving)return null;const r=rushing?statValue(rushing,'yards'):0,rec=receiving?statValue(receiving,'yards'):0;if(r===null||rec===null)return null;return r+rec}return null}

async function mlbJson(url:string){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'GameDay-Sports/1.0'}});if(!r.ok)throw new Error(`MLB ${r.status}`);return await r.json()}
async function matchMlbGame(event:any,scheduleCache:Map<string,any[]>){for(const off of [0,-1,1]){const date=isoDateAt(String(event.commence_time),off);if(!scheduleCache.has(date)){const d=await mlbJson(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${date}`);const all:any[]=[];for(const day of d?.dates??[])for(const g of day?.games??[])all.push(g);scheduleCache.set(date,all)}for(const g of scheduleCache.get(date)??[]){const home=clean(g?.teams?.home?.team?.name),away=clean(g?.teams?.away?.team?.name);if(norm(home)===norm(event.home_team)&&norm(away)===norm(event.away_team))return g}}return null}
async function fetchMlbBox(gamePk:string,cache:Map<string,any>){if(cache.has(gamePk))return cache.get(gamePk);const box=await mlbJson(`https://statsapi.mlb.com/api/v1/game/${encodeURIComponent(gamePk)}/boxscore`);cache.set(gamePk,box);return box}
function findMlbPlayer(box:any,playerName:string,kind:'batting'|'pitching'){const target=norm(playerName);for(const side of ['away','home']){const team=box?.teams?.[side],pitcherIds=new Set((team?.pitchers??[]).map((id:any)=>String(id)));for(const p of Object.values(team?.players??{}) as any[]){if(norm(p?.person?.fullName)!==target)continue;if(kind==='batting'){const b=p?.stats?.batting;if(!b||!Object.keys(b).length||Number(b?.plateAppearances??0)<=0)return null;return b}else{if(!pitcherIds.has(String(p?.person?.id??'')))return null;const x=p?.stats?.pitching;if(!x||!Object.keys(x).length)return null;return x}}}return null}
function mlbPropActual(key:string,box:any,player:string){if(key.startsWith('pitcher_')){const x=findMlbPlayer(box,player,'pitching');if(!x)return null;if(key==='pitcher_outs')return num(x.outs);if(key==='pitcher_strikeouts_alternate')return num(x.strikeOuts);return null}const b=findMlbPlayer(box,player,'batting');if(!b)return null;if(key==='batter_doubles_alternate')return num(b.doubles);if(key==='batter_hits'||key==='batter_hits_alternate')return num(b.hits);if(key==='batter_home_runs')return num(b.homeRuns);if(key==='batter_rbis'||key==='batter_rbis_alternate')return num(b.rbi);if(key==='batter_runs_scored_alternate')return num(b.runs);if(key==='batter_total_bases'||key==='batter_total_bases_alternate')return num(b.totalBases);if(key==='batter_hits_runs_rbis_alternate'){const h=num(b.hits),r=num(b.runs),rbi=num(b.rbi);return h===null||r===null||rbi===null?null:h+r+rbi}return null}

Deno.serve(async(req:Request)=>{if(req.method!=='POST')return reply({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),oddsKey=Deno.env.get('ODDS_API_KEY'),sportsKey=Deno.env.get('API_SPORTS_KEY');if(!url||!service||!oddsKey||!sportsKey)return reply({error:'Settlement backend is not configured'},503);const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:secretRow,error:secretError}=await admin.from('internal_job_secrets').select('secret').eq('name','auto-settle-test-wagers').single();if(secretError||!secretRow?.secret)return reply({error:'Settlement job secret unavailable'},503);if(req.headers.get('x-gameday-job-token')!==secretRow.secret)return reply({error:'Unauthorized'},401);
const{data:wagers,error:wagerError}=await admin.from('wagers').select('id,wager_type,stake,potential_return,status,wager_selections(id,event_id,event_name,sport_key,market_key,selection_name,description,point,american_odds)').eq('is_test',true).in('status',['pending','accepted']).order('placed_at',{ascending:true}).limit(100);if(wagerError)return reply({error:wagerError.message},500);if(!wagers?.length)return reply({ok:true,checked:0,settled:0,skipped_pending:0,skipped_unsupported:0});
const sports=new Set<string>();for(const w of wagers)for(const s of w.wager_selections??[]){const sk=clean(s.sport_key).toLowerCase(),mk=clean(s.market_key);const canonical=resolveGradingSport(sk);if(canonical&&(STANDARD_MARKETS.has(mk)||isFootballProp(mk,sk)||isMlbProp(mk,sk)))sports.add(canonical)}const scoresBySport=new Map<string,Map<string,any>>();await Promise.all([...sports].map(async sport=>{const rows=await fetchScores(sport,oddsKey);scoresBySport.set(sport,new Map(rows.map((g:any)=>[String(g.id),g])))}));
const propEventIds=[...new Set(wagers.flatMap((w:any)=>(w.wager_selections??[]).filter((s:any)=>{const sk=clean(s.sport_key).toLowerCase(),mk=clean(s.market_key);return isFootballProp(mk,sk)||isMlbProp(mk,sk)}).map((s:any)=>String(s.event_id))))];const eventsById=new Map<string,any>();if(propEventIds.length){const{data:events}=await admin.from('sports_events').select('provider_event_id,commence_time,home_team,away_team,status').in('provider_event_id',propEventIds);for(const e of events??[])eventsById.set(String(e.provider_event_id),e)}
const apiGamesByDate=new Map<string,any[]>(),footballStatsByGame=new Map<string,any[]>(),mlbScheduleCache=new Map<string,any[]>(),mlbBoxCache=new Map<string,any>();let settled=0,skippedPending=0,skippedUnsupported=0;const results:any[]=[];
for(const w of wagers){const selections=w.wager_selections??[];if(!selections.length){skippedUnsupported++;continue}const grades:any[]=[];let waiting=false,unsupported=false;for(const s of selections){const sport=resolveGradingSport(s.sport_key),market=clean(s.market_key);if(!sport){unsupported=true;break}const oddsGame=scoresBySport.get(sport)?.get(String(s.event_id));if(!oddsGame||!oddsGame.completed){waiting=true;break}if(STANDARD_MARKETS.has(market)){const grade=gradeStandard(s,oddsGame);if(!grade){unsupported=true;break}grades.push(grade);continue}const event=eventsById.get(String(s.event_id));if(!event){waiting=true;break}
if(isFootballProp(market,sport)){let apiGame:any;try{apiGame=await matchApiFootballGame(event,sportsKey,apiGamesByDate)}catch{waiting=true;break}if(!apiGame||!['FT','AOT','AP'].includes(apiGameStatus(apiGame))){waiting=true;break}const gameId=clean(apiGame?.game?.id??apiGame?.id);if(!gameId){waiting=true;break}let statRows:any[];try{statRows=await fetchFootballPlayerStats(gameId,sportsKey,footballStatsByGame)}catch{waiting=true;break}const actual=footballPropActual(market,statRows,clean(s.description));if(actual===null){waiting=true;break}const grade=gradeThreshold(s,actual,oddsGame);if(!grade){unsupported=true;break}grades.push(grade);continue}
if(isMlbProp(market,sport)){let mg:any;try{mg=await matchMlbGame(event,mlbScheduleCache)}catch{waiting=true;break}const final=String(mg?.status?.abstractGameState??'').toLowerCase()==='final'||String(mg?.status?.detailedState??'').toLowerCase().includes('final');if(!mg?.gamePk||!final){waiting=true;break}let box:any;try{box=await fetchMlbBox(String(mg.gamePk),mlbBoxCache)}catch{waiting=true;break}const actual=mlbPropActual(market,box,clean(s.description));if(actual===null){waiting=true;break}const grade=gradeThreshold(s,actual,oddsGame);if(!grade){unsupported=true;break}grades.push(grade);continue}
unsupported=true;break}
if(waiting){skippedPending++;continue}if(unsupported||grades.length!==selections.length){skippedUnsupported++;continue}const anyLost=grades.some(g=>g.result==='lost'),allVoid=grades.every(g=>g.result==='void'),result=anyLost?'lost':allVoid?'void':'won';let credit=0;if(result==='void')credit=Number(w.stake);else if(result==='won'){let dec=1;for(let i=0;i<grades.length;i++)if(grades[i].result==='won')dec*=decimalFromAmerican(Number(selections[i].american_odds));credit=Math.round(Number(w.stake)*dec*100)/100}const{data:settlement,error:settleError}=await admin.rpc('settle_test_wager_auto_atomic',{p_wager_id:w.id,p_result:result,p_credit:credit,p_grades:grades});if(settleError){results.push({wager_id:w.id,error:settleError.message});continue}settled++;results.push({wager_id:w.id,result,credit,settlement:Array.isArray(settlement)?settlement[0]:settlement})}
return reply({ok:true,checked:wagers.length,settled,skipped_pending:skippedPending,skipped_unsupported:skippedUnsupported,results});});
