// Actual pinned Supabase SDK; only Auth/wallet HTTP responses are test fixtures.
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const{chromium}=require('playwright');const root=path.resolve(__dirname,'..'),sdkFile=path.join(root,'node_modules/@supabase/supabase-js/dist/umd/supabase.js');
const storageKey='sb-qsvrvhcklnsbekxblpfo-auth-token';let server,browser,base;
const user=id=>({id:id==='A'?'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa':'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',email:id+'@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{}});
function session(id='A',suffix=''){const u=user(id),expires=Math.floor(Date.now()/1000)+3600;return{access_token:[{alg:'HS256',typ:'JWT'},{sub:u.id,exp:expires,role:'authenticated',iss:'fixture',suffix}].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.')+'.fixture',refresh_token:'fixture-refresh-'+id+suffix,token_type:'bearer',expires_in:3600,expires_at:expires,user:u}}
const sdkModule=()=>fs.readFileSync(sdkFile,'utf8')+`\nexport function createClient(...args){const client=supabase.createClient(...args);globalThis.__client=client;globalThis.__sdkEvents=[];client.auth.onAuthStateChange((event)=>__sdkEvents.push(event));const signOut=client.auth.signOut.bind(client.auth);client.auth.signOut=(options)=>{if(options?.scope==='local'&&globalThis.__injectStoredSession){localStorage.setItem(client.storageKey,JSON.stringify(__injectStoredSession));globalThis.__injectStoredSession=null}return signOut(options)};return client}\n`;
test.before(async()=>{assert.equal(JSON.parse(fs.readFileSync(path.join(root,'node_modules/@supabase/supabase-js/package.json'),'utf8')).version,'2.117.3');server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');if(url.pathname==='/fixture-sdk.mjs'){res.setHeader('Content-Type','text/javascript');res.end(sdkModule());return}if(url.pathname==='/consumer.html'){res.setHeader('Content-Type','text/html');res.end(`<script type="module">import{createClient}from'./fixture-sdk.mjs';import{GAMEDAY_CONFIG as C}from'./gameday-config.js';const client=createClient(C.supabaseUrl,C.supabasePublishableKey);const {data,error}=await client.auth.getSession();window.__consumer={session:data.session,error:error?.message||null};</script>`);return}if(url.pathname==='/empty.html'){res.end('<!doctype html><title>Fixture</title>');return}const filename=path.join(root,decodeURIComponent(url.pathname));if(!filename.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(filename))}catch{res.writeHead(404).end()}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']})});
test.after(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve))});
async function open(t,{logout='success',holdRefresh=false}={}){
 let resolveHeld;const heldReady=new Promise(resolve=>resolveHeld=resolve);const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),calls=[],held=[];t.after(async()=>{for(const release of held)release();await context.close()});
 await context.addInitScript(()=>{window.__transport=[];const nativeFetch=window.fetch.bind(window);window.fetch=(input,options)=>{const call={url:String(input),aborted:!!options?.signal?.aborted};window.__transport.push(call);options?.signal?.addEventListener('abort',()=>{call.aborted=true;call.reason=options.signal.reason?.name},{once:true});return nativeFetch(input,options)}});
 await context.route('https://**/*',async route=>{
  const req=route.request(),url=new URL(req.url());if(url.pathname.includes('/@supabase/supabase-js@'))return route.fulfill({contentType:'text/javascript',body:`export{createClient}from'${base}/fixture-sdk.mjs';`});
  calls.push({url:url.pathname,method:req.method(),authorization:req.headers().authorization,search:url.search});
  const json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
  if(url.pathname.endsWith('/auth/v1/logout')){if(logout==='fail')return route.abort('failed');if(logout==='stall'){await new Promise(resolve=>held.push(resolve));try{return await route.fulfill({status:204,body:''})}catch{return}}return route.fulfill({status:204,body:''})}
  if(url.pathname.endsWith('/auth/v1/token')){if(holdRefresh){const answer=await new Promise(resolve=>{held.push(resolve);resolveHeld()});try{return await json(answer||session('A','rotated'),answer?.status||200)}catch{return}}return json({message:'Fixture refresh unavailable'},503)}
  if(url.pathname.endsWith('/auth/v1/user')){const token=req.headers().authorization?.slice(7);return json(token===sessionB.access_token?user('B'):user('A'))}
  if(url.pathname.endsWith('/rest/v1/wallets'))return json({balance:24});
  if(url.pathname.endsWith('/rest/v1/wallet_transactions'))return json([]);
  if(url.pathname.endsWith('/rest/v1/wagers'))return json([{id:'fixture-wager-A',user_id:user('A').id,wager_type:'single',stake:5,potential_return:10,status:'accepted',is_test:true,placed_at:'2026-10-10T12:00:00Z',wager_selections:[{selection_name:'A private pick',event_name:'A private event',market_key:'h2h',american_odds:100}]}]);
  if(url.pathname.endsWith('/rest/v1/wager_selections'))return json([]);
  return route.abort();
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(base+'/empty.html');await page.evaluate(({key,s})=>{localStorage.setItem(key,JSON.stringify(s));localStorage.setItem(key+'-user',JSON.stringify({user:s.user}));localStorage.setItem(key+'-code-verifier','fixture-pkce');localStorage.setItem('unrelated-preference','keep')},{key:storageKey,s:sessionA});await page.goto(base+'/gameday-auth.html');await page.waitForFunction(()=>document.querySelector('#walletBalance').textContent==='$24.00');t.after(()=>assert.deepEqual(errors,[]));return{page,context,calls,held,heldReady};
}
const sessionA=session('A'),sessionB=session('B');
async function absent(page){assert.equal(await page.evaluate(key=>localStorage.getItem(key),storageKey),null);assert.equal(await page.evaluate(()=>localStorage.getItem('unrelated-preference')),'keep');assert((await page.evaluate(()=>__sdkEvents)).includes('SIGNED_OUT'))}
async function consumer(context,id=null){const p=await context.newPage();await p.goto(base+'/consumer.html');await p.waitForFunction(()=>!!window.__consumer);assert.equal(await p.evaluate(()=>__consumer.error),null);assert.equal(await p.evaluate(()=>__consumer.session?.user?.email||null),id?id+'@example.invalid':null);return p}
test('Pinned SDK normal failed logout clears persisted credentials and emits SIGNED_OUT',async t=>{const{page,context,calls}=await open(t,{logout:'fail'});const error=await page.evaluate(async()=>{const{error}=await __client.auth.signOut();return error?.name});assert.equal(error,'AuthRetryableFetchError');await absent(page);assert.equal(calls.filter(c=>c.url.endsWith('/logout')).length,1);await consumer(context)});
test('Pinned SDK stalled logout is actually aborted and clears persisted credentials', {timeout:25000},async t=>{const{page,context}=await open(t,{logout:'stall'});const error=await page.evaluate(async()=>{const{error}=await __client.auth.signOut();return error?.name});assert.equal(error,'AuthRetryableFetchError');assert(await page.evaluate(()=>__transport.some(c=>c.url.includes('/logout')&&c.aborted&&c.reason==='TimeoutError')));await absent(page);await consumer(context)});
test('Account removes credentials immediately during stalled logout, broadcasts, and prevents navigation/new-tab recovery',{timeout:25000},async t=>{
 const{page,context,calls}=await open(t,{logout:'stall'});const listening=await consumer(context,'A');await page.click('#signoutBtn');
 await page.waitForFunction(()=>__sdkEvents.includes('SIGNED_OUT'),undefined,{timeout:5000});await absent(page);assert(await page.locator('#signinBtn').isDisabled());
 await listening.waitForFunction(()=>__sdkEvents.includes('SIGNED_OUT'),undefined,{timeout:5000});assert.equal(await listening.evaluate(async()=>{const{data}=await __client.auth.getSession();return data.session}),null);await consumer(context);
 const navigation=await context.newPage();await navigation.goto(base+'/gameday-my-bets.html');await navigation.waitForFunction(()=>/sign in/i.test(document.querySelector('#status').textContent),undefined,{timeout:5000});assert(!await navigation.locator('body').textContent().then(text=>text.includes('A@example.invalid')));assert.equal(calls.filter(c=>c.url.endsWith('/wagers')).length,0);
 await page.waitForFunction(()=>__transport.some(c=>c.url.includes('/logout')&&c.aborted),undefined,{timeout:18000});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Unable to finish'),undefined,{timeout:5000});assert(await page.locator('#signinBtn').isEnabled());await absent(page)
});
test('Pinned SDK early refresh error can retain a session; Account signout clears it through supported storage/SDK cleanup',{timeout:15000},async t=>{const{page,context,calls,held,heldReady}=await open(t,{holdRefresh:true});await page.evaluate(async key=>{await __client.auth.stopAutoRefresh();const s=JSON.parse(localStorage.getItem(key));s.expires_at=1;localStorage.setItem(key,JSON.stringify(s))},storageKey);await page.clock.install();const signout=page.evaluate(async()=>{const{error}=await __client.auth.signOut();return error?.name});await page.waitForFunction(()=>__transport.some(c=>c.url.includes('/token')));await heldReady;await page.clock.fastForward(35000);held[0]({status:503,message:'Fixture refresh unavailable'});assert.equal(await signout,'AuthRetryableFetchError');assert.notEqual(await page.evaluate(key=>localStorage.getItem(key),storageKey),null);assert(!(await page.evaluate(()=>__sdkEvents)).includes('SIGNED_OUT'));await page.click('#signoutBtn');await page.waitForFunction(()=>__sdkEvents.includes('SIGNED_OUT'));await absent(page);assert.equal(calls.filter(c=>c.url.endsWith('/token')).length,1);await consumer(context)});
test('Account late refresh cannot recreate storage and already-open My Bets clears before that reply',async t=>{
 const{page,context,held,heldReady}=await open(t,{holdRefresh:true});const bets=await context.newPage();await bets.goto(base+'/gameday-my-bets.html');await bets.waitForFunction(()=>document.querySelector('#openBets').textContent.includes('A private pick'));
 const refresh=page.evaluate(async()=>{const result=await __client.auth.refreshSession();return{session:result.data.session,error:result.error?.name}});await page.waitForFunction(()=>__transport.some(c=>c.url.includes('/token')));await page.click('#signoutBtn');await page.waitForFunction(()=>__sdkEvents.includes('SIGNED_OUT'));await absent(page);
 await bets.waitForFunction(()=>/sign in/i.test(document.querySelector('#status').textContent)&&!document.querySelector('body').textContent.includes('A private pick'),undefined,{timeout:2000});assert(!await bets.locator('body').textContent().then(text=>text.includes('A@example.invalid')));
 await heldReady;held[0](session('A','rotated'));const result=await refresh;assert.equal(result.session,null);await absent(page);await consumer(context);assert(!await bets.locator('body').textContent().then(text=>text.includes('A private pick')))
});
test('Account storage cleanup preserves a different account arriving before SDK cleanup reads',async t=>{const{page,context,calls}=await open(t);await page.evaluate(s=>{window.__injectStoredSession=s},sessionB);await page.click('#signoutBtn');await page.waitForFunction(()=>__sdkEvents.includes('SIGNED_OUT'));assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).access_token,storageKey),sessionB.access_token);assert(calls.filter(c=>c.url.endsWith('/logout')).every(c=>c.authorization==='Bearer '+sessionA.access_token));await consumer(context,'B')});
test('SDK transport preserves caller cancellation while adding its own timeout',async t=>{const{page}=await open(t);const result=await page.evaluate(async()=>{const controller=new AbortController();controller.abort();const{error}=await __client.from('wallet_transactions').select('id').abortSignal(controller.signal);return error?.message});assert.match(result,/AbortError/);assert(await page.evaluate(()=>__transport.some(c=>c.url.includes('wallet_transactions')&&c.aborted))) });
test('Actual SDK fresh password recovery persists its session after a prior local signout fence',async t=>{const{page}=await open(t);const recovered=session('A','recovery');await page.evaluate(key=>{localStorage.removeItem(key);sessionStorage.setItem('gameday-account-signed-out','1')},storageKey);const hash=new URLSearchParams({access_token:recovered.access_token,refresh_token:recovered.refresh_token,expires_in:'3600',token_type:'bearer',type:'recovery'});await page.goto(base+'/empty.html');await page.goto(base+'/gameday-auth.html#'+hash);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Recovery link verified'),undefined,{timeout:5000});assert(await page.locator('#recoveryPanel').isVisible());assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).access_token,storageKey),recovered.access_token);assert.equal(await page.evaluate(()=>sessionStorage.getItem('gameday-account-signed-out')),null);assert.equal(await page.evaluate(async()=>{const{data}=await __client.auth.getSession();return data.session.access_token}),recovered.access_token);assert((await page.evaluate(()=>__sdkEvents)).includes('PASSWORD_RECOVERY'))});
