// Browser customer-flow regressions. SDK, Auth and wallet services use local fixtures.
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const{chromium}=require('playwright');const root=path.resolve(__dirname,'..');let server,browser,base;
const sdk=`export function createClient(){__clients++;const unlocked=()=>{if(__authLock)throw Error('SDK called inside auth notification')};const result=(action,value)=>{unlocked();return __action(action,value)};
return{auth:{
 getSession:()=>result('session',{data:{session:structuredClone(__session)},error:__sessionError}),
 getUser:token=>{const owner=token?.replace('fixture-','').split('-')[0],user=structuredClone(__users[owner]);return result('user:'+token,{data:{user},error:__userErrors[token]||null})},
 onAuthStateChange(fn){__authCallbacks.push(fn);if(location.hash.includes('type=recovery'))setTimeout(()=>__emit('PASSWORD_RECOVERY',__session),0);return{data:{subscription:{unsubscribe(){}}}}},
 signOut:async()=>{const answer=await result('localSignout',{error:null});__emit('SIGNED_OUT',null);return answer},admin:{signOut:()=>result('signout',{error:__signoutError})},
 signInWithPassword:async({email})=>{const session={user:{id:'A',email},access_token:'fixture-A'};const answer=await result('signin',{data:{user:session.user,session},error:__signinError});if(!answer.error)__emit('SIGNED_IN',session);return answer},
 signUp:()=>result('signup',{data:{session:null,user:null},error:null}),resetPasswordForEmail:(email,options)=>{__calls.push({action:'resetPayload',email,options});return result('reset',{error:null})}
},from(table){unlocked();const q={table,owner:__session?.user.id,filters:[],fields:'',orders:[],limitValue:null,select(fields){this.fields=fields;return this},eq(...args){this.filters.push(args);return this},order(field,options){this.orders.push({field,...options});return this},limit(value){this.limitValue=value;return this},or(value){this.cursor=value;return this},single(){return __query(this)},then(resolve,reject){return __query(this).then(resolve,reject)}};return q},functions:{invoke:async(name,options)=>{
 unlocked();const owner=options.headers.Authorization.replace('Bearer fixture-','').split('-')[0],plan=structuredClone(__refillPlan);__calls.push({action:'refillPayload',owner,options});const answer=await result('refill',plan);if(answer.balance!==undefined)__fixtures[owner].wallets.balance=answer.balance;
 if(answer.status&&answer.status!==200)return{data:null,error:{name:'FunctionsHttpError',context:{status:answer.status,clone:()=>({json:async()=>answer.body})}}};
 if(answer.body?.ok){__fixtures[owner].wallets.balance=answer.body.balance;__fixtures[owner].wallet_transactions.unshift({id:'ffffffff-ffff-4000-8000-ffffffffffff',user_id:owner,transaction_type:'adjustment',amount:answer.body.credited,balance_after:answer.body.balance,note:'Test credit refill',created_at:new Date().toISOString()})}return{data:answer.body,error:null}
}}}}`;
function transactions(count,owner='A',at='2026-10-10T12:00:00.000Z'){return Array.from({length:count},(_,i)=>({id:`${owner==='A'?'a':'b'}0000000-0000-4000-8000-${(count-i).toString(16).padStart(12,'0')}`,user_id:owner,transaction_type:'adjustment',amount:1,balance_after:24,note:owner+' private transaction '+(count-i),created_at:at,wager_id:null}))}
test.before(async()=>{server=http.createServer((req,res)=>{const filename=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname));if(!filename.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(filename))}catch{res.writeHead(404).end()}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']})});
test.after(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve))});
async function open(t,{signedOut=false,sdkFailures=0,nestedFailures=0,sdkHold=false,userError=null,sessionError=null,rows=transactions(1),actions=[],queries=[],hash='',fakeClock=false}={}){
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});t.after(()=>context.close());
 await context.addInitScript(({signedOut,userError,sessionError,rows,actions,queries})=>{
  window.__users={A:{id:'A',email:'A@example.invalid'},B:{id:'B',email:'B@example.invalid'}};window.__user=(id,token='fixture-'+id)=>({user:__users[id],access_token:token});window.__session=signedOut?null:__user('A');window.__clients=0;window.__authCallbacks=[];window.__authLock=false;window.__sessionError=sessionError;window.__userErrors={'fixture-A':userError};window.__signoutError=null;window.__signinError=null;window.__calls=[];window.__gatedActions=actions;window.__gatedQueries=queries;window.__pendingActions=[];window.__pendingQueries=[];window.__queryErrors={};
  window.__fixtures={A:{wallets:{balance:24},wallet_transactions:rows},B:{wallets:{balance:500},wallet_transactions:[{id:'b0000000-0000-4000-8000-000000000001',user_id:'B',transaction_type:'adjustment',amount:500,note:'B private wallet note',created_at:'2026-10-10T12:00:00.000Z'}]}};
  window.__refillPlan={status:200,body:{ok:true,credited:976,balance:1000,next_refill_at:new Date(Date.now()+86400000).toISOString()}};
  window.__action=async(action,value)=>{__calls.push({action});if(__gatedActions.includes(action))await new Promise(resolve=>__pendingActions.push({action,resolve}));return value};
  window.__query=async q=>{
   const kind=q.table==='wallets'?'wallet':q.fields==='created_at'?'cooldown':'history',key=q.owner+':'+kind;let data=structuredClone(__fixtures[q.owner]?.[q.table]);
   if(Array.isArray(data)){for(const[field,value]of q.filters)data=data.filter(x=>x[field]===value);data.sort((a,b)=>b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id));if(q.cursor){const match=q.cursor.match(/^created_at\.lt\.([^,]+),and\(created_at\.eq\.([^,]+),id\.lt\.([^)]*)\)$/);if(!match)throw Error('Malformed history cursor');data=data.filter(x=>x.created_at<match[1]||x.created_at===match[2]&&x.id<match[3])}if(q.limitValue)data=data.slice(0,q.limitValue)}
   __calls.push({action:'query',kind,owner:q.owner,fields:q.fields,filters:q.filters,orders:q.orders,cursor:q.cursor,limit:q.limitValue});const error=__queryErrors[key]||null;if(__gatedQueries.includes(key))await new Promise(resolve=>__pendingQueries.push({key,resolve}));return{data,error};
  };
  window.__releaseAction=action=>{__gatedActions=__gatedActions.filter(x=>x!==action);for(const x of __pendingActions.filter(x=>x.action===action))x.resolve();__pendingActions=__pendingActions.filter(x=>x.action!==action)};
  window.__releaseQuery=key=>{__gatedQueries=__gatedQueries.filter(x=>x!==key);for(const x of __pendingQueries.filter(x=>x.key===key))x.resolve();__pendingQueries=__pendingQueries.filter(x=>x.key!==key)};
  window.__emit=(event,session)=>{__session=session;__authLock=true;try{for(const fn of __authCallbacks)fn(event,session)}finally{__authLock=false}};
 },{signedOut,userError,sessionError,rows,actions,queries});
 const sdkRequests=[],nestedRequests=[],sdkReleases=[];await context.route('https://**/*',async route=>{
  const request=route.request();if(request.url()==='https://sdk-fixture.invalid/dependency.js'){nestedRequests.push(request.url());if(nestedFailures-->0)return route.abort();return route.fulfill({contentType:'text/javascript',body:'export const dependency=true;'})}
  if(request.url().includes('/@supabase/supabase-js@')){sdkRequests.push(request.url());if(sdkHold&&sdkRequests.length===1){await request.frame().evaluate(()=>{window.__sdkNetworkStarted=true});await new Promise(resolve=>sdkReleases.push(resolve))}if(sdkFailures-->0)return route.abort();return route.fulfill({contentType:'text/javascript',body:(nestedRequests.length||nestedFailures>0?`import {dependency} from 'https://sdk-fixture.invalid/dependency.js';\n`:'')+sdk})}
  if(request.url().endsWith('/auth/v1/user')){const answer=await request.frame().evaluate(()=>__action('password',{id:__session?.user.id}));return route.fulfill({contentType:'application/json',body:JSON.stringify(answer)})}return route.abort();
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));if(fakeClock)await page.clock.install();await page.goto(base+'/gameday-auth.html'+hash,{waitUntil:'commit'});t.after(()=>assert.deepEqual(errors,[]));return{page,sdkRequests,nestedRequests,sdkReleases};
}
async function ready(p,owner='A'){await p.waitForFunction(owner=>document.querySelector('#accountEmail').textContent===owner+'@example.invalid'&&document.querySelector('#walletBalance').textContent===(owner==='A'?'$24.00':'$500.00'),owner)}
async function flush(p){await p.waitForTimeout(60)}
async function noPrivate(p){assert.equal(await p.locator('#walletBalance').textContent(),'—');assert.equal(await p.locator('#accountEmail').textContent(),'—');assert(!await p.locator('#transactions').textContent().then(s=>s.includes('private')));assert(!await p.locator('#accountPanel').isVisible())}
test('Account SDK failure presents a usable full-document retry',async t=>{const{page,sdkRequests}=await open(t,{sdkFailures:1});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('reconnect'));assert(await page.locator('#retryConnection').isEnabled());assert(await page.locator('#signinBtn').isDisabled());await page.click('#retryConnection');await ready(page);assert.equal(sdkRequests.length,2)});
test('Account reload clears a failed nested ESM dependency and preserves recovery URL',async t=>{const hash='#type=recovery&access_token=fixture-A';const{page,nestedRequests}=await open(t,{nestedFailures:1,hash});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('reconnect'));assert(!await page.locator('#status').textContent().then(s=>s.includes('expired')));assert.equal(new URL(page.url()).hash,hash);await page.click('#retryConnection');await page.waitForFunction(()=>!document.querySelector('#recoveryPanel').classList.contains('hidden'));assert.equal(new URL(page.url()).hash,hash);assert.equal(nestedRequests.length,2)});
test('Account bounds a stalled server verification and retries without false expiry',async t=>{const{page}=await open(t,{actions:['user:fixture-A'],fakeClock:true,hash:'#type=recovery&access_token=fixture-A'});await page.waitForFunction(()=>__pendingActions.length>0);await page.clock.fastForward(13000);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Unable to verify'));await noPrivate(page);assert(!await page.locator('#status').textContent().then(s=>s.includes('expired')));await page.evaluate(()=>{__gatedActions=[]});await page.click('#retryConnection');await page.waitForFunction(()=>!document.querySelector('#recoveryPanel').classList.contains('hidden'));await page.evaluate(()=>__releaseAction('user:fixture-A'))});
test('Account does not display active status or private data before getUser succeeds',async t=>{const{page}=await open(t,{actions:['user:fixture-A']});await page.waitForFunction(()=>__pendingActions.length===1);await noPrivate(page);assert(!await page.locator('#status').textContent().then(s=>s.includes('account is active')));assert.equal(await page.evaluate(()=>__calls.filter(c=>c.action==='query').length),0);await page.evaluate(()=>__releaseAction('user:fixture-A'));await ready(page)});
test('Account expired server token shows sign-in instead of a locally cached active account',async t=>{const{page}=await open(t,{userError:{status:401,code:'bad_jwt',message:'JWT expired'}});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('session expired'));await noPrivate(page);assert(await page.locator('#authForms').isVisible());assert.equal(await page.evaluate(()=>__calls.filter(c=>c.action==='query').length),0)});
test('Account temporary getUser network failure stays distinct from expiry and recovers',async t=>{const{page}=await open(t,{userError:{name:'AuthRetryableFetchError',message:'Failed to fetch'}});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Unable to verify'));await noPrivate(page);assert(!await page.locator('#status').textContent().then(s=>s.includes('expired')));await page.evaluate(()=>{__userErrors={}});await page.click('#retryConnection');await ready(page)});
test('Account rejects an older same-owner token 401 after a new token arrives',async t=>{const{page}=await open(t,{userError:{status:401},actions:['user:fixture-A']});await page.waitForFunction(()=>__pendingActions.length===1);await page.evaluate(()=>__emit('TOKEN_REFRESHED',__user('A','fixture-A-new')));await ready(page);await page.evaluate(()=>__releaseAction('user:fixture-A'));await flush(page);await ready(page);assert.match(await page.locator('#status').textContent(),/account is active/)});
test('Account delayed server verification for A cannot overwrite B or A-B-A',async t=>{const{page}=await open(t,{actions:['user:fixture-A']});await page.waitForFunction(()=>__pendingActions.length===1);await page.evaluate(()=>__emit('SIGNED_IN',__user('B')));await ready(page,'B');await page.evaluate(()=>{__gatedActions=[];__emit('SIGNED_IN',__user('A','fixture-A-new'))});await ready(page);await page.evaluate(()=>__releaseAction('user:fixture-A'));await flush(page);await ready(page)});
test('Account invalid reset URL explains the problem and provides a new-link flow',async t=>{const{page}=await open(t,{signedOut:true,hash:'#error=access_denied&error_code=otp_expired&error_description=expired'});await page.waitForFunction(()=>document.querySelector('#resetIssue').classList.contains('hidden')===false);assert.match(await page.locator('#resetIssueText').textContent(),/invalid or expired/);assert(!await page.locator('#recoveryPanel').isVisible());await page.click('#requestNewResetLink');await page.fill('#resetEmail','A@example.invalid');await page.click('#resetEmailBtn');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('reset link has been sent'));const payload=await page.evaluate(()=>__calls.find(c=>c.action==='resetPayload'));assert.equal(payload.options.redirectTo,base+'/gameday-auth.html');assert(!new URL(page.url()).hash)});
test('Account expired recovery session clears verified password UI',async t=>{const{page}=await open(t,{userError:{status:401,code:'bad_jwt'},hash:'#type=recovery&access_token=fixture-A'});await page.waitForFunction(()=>document.querySelector('#resetIssue').classList.contains('hidden')===false);assert.match(await page.locator('#resetIssueText').textContent(),/reset link expired/);assert(!await page.locator('#recoveryPanel').isVisible());assert(await page.locator('#requestNewResetLink').isVisible())});
test('Account input labels, signup privacy, direct test mode, and help links are accessible',async t=>{const{page}=await open(t,{signedOut:true});await page.waitForFunction(()=>document.querySelector('#status').textContent==='You are not signed in.');for(const id of ['signupEmail','signupPassword','signinEmail','signinPassword','resetEmail','newPassword','confirmPassword'])assert.equal(await page.locator('#'+id).evaluate(el=>el.labels.length),1);assert.match(await page.locator('header').textContent(),/TEST MODE.*no real money/);assert.equal(await page.getByRole('link',{name:'Privacy Notice'}).getAttribute('href'),'gameday-privacy.html');assert(await page.locator('a[href="gameday-help.html"]').count());assert(await page.locator('a[href="gameday-settings.html"]').count());assert.equal(await page.getByRole('link',{name:'View Casino History',includeHidden:true}).getAttribute('href'),'gameday-casino-history.html')});
test('Account recent refill ledger disables credits and displays the next eligible time',async t=>{const recent=new Date(Date.now()-3600000).toISOString(),rows=[{...transactions(1)[0],note:'Test credit refill',created_at:recent}];const{page}=await open(t,{rows});await ready(page);assert(await page.locator('#refillWallet').isDisabled());assert.match(await page.locator('#refillNotice').textContent(),/Next refill available/);const q=await page.evaluate(()=>__calls.find(c=>c.action==='query'&&c.kind==='cooldown'));assert(q.filters.some(f=>f[0]==='user_id'&&f[1]==='A'));assert(q.filters.some(f=>f[0]==='note'&&f[1]==='Test credit refill'))});
test('Account retains authoritative non-2xx cooldown body and does not re-enable refill',async t=>{const{page}=await open(t);await ready(page);await page.evaluate(()=>{__refillPlan={status:429,body:{ok:false,code:'REFILL_COOLDOWN',error:'Next refill available tomorrow',next_refill_at:new Date(Date.now()+82800000).toISOString()}}});await page.click('#refillWallet');await page.waitForFunction(()=>document.querySelector('#refillNotice').textContent.includes('Next refill available'));assert(await page.locator('#refillWallet').isDisabled());assert.match(await page.locator('#status').textContent(),/tomorrow/);await page.click('#refreshWallet');await ready(page);assert(await page.locator('#refillWallet').isDisabled());assert.equal(await page.evaluate(()=>__calls.filter(c=>c.action==='refillPayload').length),1)});
test('Account unknown refill availability stays disabled until a successful manual refresh',async t=>{const{page}=await open(t);await ready(page);await page.evaluate(()=>{__refillPlan={status:503,body:{ok:false,error:'Fixture refill unavailable'}}});await page.click('#refillWallet');await page.waitForFunction(()=>document.querySelector('#refillNotice').textContent.includes('Refill is unavailable'));assert(await page.locator('#refillWallet').isDisabled());await page.click('#refreshWallet');await ready(page);assert(await page.locator('#refillWallet').isEnabled())});
test('Account successful refill shows real balance and backend next eligible time',async t=>{const{page}=await open(t);await ready(page);await page.click('#refillWallet');await page.waitForFunction(()=>document.querySelector('#walletBalance').textContent==='$1000.00');assert(await page.locator('#refillWallet').isDisabled());assert.match(await page.locator('#refillNotice').textContent(),/Next refill available/);assert.match(await page.locator('#transactions').textContent(),/Test credit refill/)});
test('Account failed cooldown lookup cannot enable an unverified refill',async t=>{const{page}=await open(t);await ready(page);await page.evaluate(()=>{__queryErrors['A:cooldown']={message:'Fixture cooldown unavailable'}});await page.click('#refreshWallet');await page.waitForFunction(()=>document.querySelector('#refillNotice').textContent.includes('Unable to verify'));assert(await page.locator('#refillWallet').isDisabled());await page.evaluate(()=>{__queryErrors={}});await page.click('#refreshWallet');await ready(page);assert(await page.locator('#refillWallet').isEnabled())});
test('Account tied-time transaction pagination shows every owned row without duplication',async t=>{const{page}=await open(t,{rows:transactions(65)});await ready(page);assert.equal(await page.locator('#transactions .tx').count(),50);assert(await page.locator('#moreTransactions').isVisible());await page.click('#moreTransactions');await page.waitForFunction(()=>document.querySelectorAll('#transactions .tx').length===65);assert(!await page.locator('#moreTransactions').isVisible());assert.match(await page.locator('#historyNotice').textContent(),/all 65/);const queries=await page.evaluate(()=>__calls.filter(c=>c.action==='query'&&c.kind==='history'));assert.equal(queries.length,2);assert(queries.every(q=>q.filters.some(f=>f[0]==='user_id'&&f[1]==='A')));assert.deepEqual(queries[0].orders.map(o=>o.field),['created_at','id']);assert.match(queries[1].cursor,/id\.lt\./);assert.equal(new Set(await page.locator('.tx-meta').allTextContents()).size,65)});
test('Account earlier-history query failure retains current page and offers retry',async t=>{const{page}=await open(t,{rows:transactions(60)});await ready(page);await page.evaluate(()=>{__queryErrors['A:history']={message:'Fixture offline'}});await page.click('#moreTransactions');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('earlier transactions'));assert.equal(await page.locator('#transactions .tx').count(),50);assert(await page.locator('#moreTransactions').isEnabled());await page.evaluate(()=>{__queryErrors={}});await page.click('#moreTransactions');await page.waitForFunction(()=>document.querySelectorAll('#transactions .tx').length===60)});
test('Account late prior-owner history page and cooldown cannot paint B',async t=>{const{page}=await open(t,{rows:transactions(60)});await ready(page);await page.evaluate(()=>{__gatedQueries=['A:history']});await page.click('#moreTransactions');await page.waitForFunction(()=>__pendingQueries.length===1);await page.evaluate(()=>__emit('SIGNED_IN',__user('B')));await ready(page,'B');await page.evaluate(()=>__releaseQuery('A:history'));await flush(page);await ready(page,'B');assert.equal(await page.locator('#transactions .tx').count(),1);assert(!await page.locator('#transactions').textContent().then(s=>s.includes('A private')))});
test('Account failed signout fences former data through late token refresh and retry',async t=>{const{page}=await open(t);await ready(page);await page.evaluate(()=>{__signoutError={message:'Fixture signout offline'}});await page.click('#signoutBtn');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Unable to finish'));await page.evaluate(()=>__emit('TOKEN_REFRESHED',__user('A','fixture-A-new')));await noPrivate(page);await page.click('#retryConnection');await page.waitForFunction(()=>__calls.filter(c=>c.action==='signout').length===2);await noPrivate(page);await page.evaluate(()=>{__signoutError=null});await page.fill('#signinEmail','A@example.invalid');await page.fill('#signinPassword','GoodPass1!');await page.click('#signinBtn');await ready(page)});

test('Account stalled SDK import times out and recovers after a full reload',async t=>{
 const{page,sdkRequests,sdkReleases}=await open(t,{sdkHold:true,fakeClock:true});await page.waitForFunction(()=>window.__sdkNetworkStarted===true);await page.clock.fastForward(13000);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('reconnect'));assert(await page.locator('#retryConnection').isEnabled());assert.equal(await page.evaluate(()=>__clients),0);for(const release of sdkReleases)release();await page.click('#retryConnection');await ready(page);assert.equal(sdkRequests.length,2);
});
test('Account refill eligibility checks a recent refill outside the first history page',async t=>{
 const now=Date.now(),rows=transactions(60,'A',new Date(now-3600000).toISOString());rows.push({...transactions(1)[0],id:'c0000000-0000-4000-8000-000000000001',note:'Test credit refill',created_at:new Date(now-7200000).toISOString()});const{page}=await open(t,{rows});await ready(page);assert.equal(await page.locator('#transactions .tx').count(),50);assert(!await page.locator('#transactions').textContent().then(s=>s.includes('Test credit refill')));assert(await page.locator('#refillWallet').isDisabled());assert.match(await page.locator('#refillNotice').textContent(),/Next refill available/);
});
test('Account unavailable refill stays disabled until the server-ledger cooldown expires',async t=>{
 const recent=new Date(Date.now()-86400000+1000).toISOString(),rows=[{...transactions(1)[0],note:'Test credit refill',created_at:recent}];const{page}=await open(t,{rows,fakeClock:true});await ready(page);assert(await page.locator('#refillWallet').isDisabled());await page.clock.fastForward(3000);assert(await page.locator('#refillWallet').isEnabled());assert.equal(await page.locator('#refillNotice').textContent(),'');
});
test('Account local signout fence survives document reload after failed signout',async t=>{
 const{page}=await open(t);await ready(page);await page.evaluate(()=>{__signoutError={message:'Fixture offline'}});await page.click('#signoutBtn');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Unable to finish'));await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent==='You are not signed in.');await page.evaluate(()=>__emit('TOKEN_REFRESHED',__user('A','fixture-A-new')));await noPrivate(page);assert.equal(await page.evaluate(()=>__calls.filter(c=>c.action.startsWith('user:')).length),0);
});
