const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { PGlite } = require('@electric-sql/pglite');

const root = path.resolve(__dirname, '..');
const sql = fs.readFileSync(path.join(root, 'scripts/gameday-schema-fingerprint.sql'), 'utf8');
const saved = JSON.parse(fs.readFileSync(path.join(root, 'scripts/gameday-production-schema-fingerprint.json'), 'utf8'));
const md5 = value => crypto.createHash('md5').update(value).digest('hex');
const byteOrder = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b));
// Match PostgreSQL jsonb::text: object keys sort by UTF-8 length and bytes.
function jsonbText(value) {
  if (Array.isArray(value)) return '[' + value.map(jsonbText).join(', ') + ']';
  if (value && typeof value === 'object') return '{' + Object.keys(value).sort((a, b) => Buffer.byteLength(a) - Buffer.byteLength(b) || byteOrder(a, b)).map(key => JSON.stringify(key) + ': ' + jsonbText(value[key])).join(', ') + '}';
  return JSON.stringify(value);
}
function verifySnapshot(fingerprint) {
  assert.equal(fingerprint.schema_version, 1);
  assert.equal(fingerprint.scope, 'public_non_extension_catalog');
  assert.equal(fingerprint.definition_hash_algorithm, 'md5');
  assert.equal(fingerprint.ordering, 'kind,key COLLATE C');
  const keys = fingerprint.entries.map(entry => entry.kind + '\0' + entry.key);
  assert.equal(new Set(keys).size, keys.length, 'stable object identities are unique');
  assert.deepEqual(keys, [...keys].sort(byteOrder), 'object identities use C ordering');
  const counts = {};
  for (const entry of fingerprint.entries) {
    counts[entry.kind] = (counts[entry.kind] || 0) + 1;
    assert.equal(entry.metadata_md5, md5(jsonbText(entry.metadata)), entry.key + ' metadata hash');
  }
  assert.deepEqual(fingerprint.counts, counts);
  assert.equal(fingerprint.schema_md5, md5(jsonbText(fingerprint.entries)), 'complete schema hash covers ordered entries');
}
function entry(fingerprint, kind, key) {
  const found = fingerprint.entries.find(item => item.kind === kind && item.key === key);
  assert(found, kind + ' ' + key + ' exists');
  return found.metadata;
}
async function snapshot(db) { return (await db.query(sql)).rows[0].fingerprint; }

test('Production catalog artifact has verifiable deterministic hashes and safe metadata only', () => {
  assert.equal(saved.project_ref, 'qsvrvhcklnsbekxblpfo');
  assert.equal(saved.read_only, true);
  assert(Number.isFinite(Date.parse(saved.observed_at)));
  verifySnapshot(saved.fingerprint);
  const encoded = JSON.stringify(saved);
  assert(!/\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b|\bsb_secret_[A-Za-z0-9_-]+\b/.test(encoded));
  assert(!/"(?:headers|schedule|prosrc|probin|adbin|body|definition|row_data)"\s*:/.test(encoded), 'no literal definitions, scheduled requests or application rows');
  const v2 = saved.fingerprint.entries.find(item => item.kind === 'routine' && item.key.startsWith('public.start_blackjack_test_hand_v2('));
  const v3 = saved.fingerprint.entries.find(item => item.kind === 'routine' && item.key.startsWith('public.advance_blackjack_test_hand_v3('));
  assert(v2 && v3, 'live v2 and v3 Blackjack routine signatures are independently recorded');
  assert.notEqual(v2.metadata.body_md5, v3.metadata.body_md5);
});

test('Fingerprint SQL is one catalog-only statement with transaction-local deparse settings', () => {
  const withoutComments = sql.replace(/^\s*--.*$/gm, '');
  assert.match(withoutComments, /^\s*with\b/i);
  assert.equal(withoutComments.split(';').filter(part => part.trim()).length, 1);
  assert(!/\b(?:insert|update|delete|truncate|alter|create|drop|execute)\b/i.test(withoutComments));
  assert(!/\b(?:auth\.|cron\.|net\.|pg_read_file|pg_stat_activity|last_value|nextval|currval)\b/i.test(withoutComments));
  assert.match(sql, /set_config\('search_path', 'pg_catalog', true\)/);
  assert.match(sql, /not t\.tgisinternal/);
  assert.match(sql, /d\.deptype = 'e'/);
});

test('Isolated PostgreSQL fixture verifies catalog coverage, redaction and change detection', async t => {
  const db = new PGlite();
  await db.waitReady;
  const marker = 'private_literal_fixture_5e91aa32';
  try {
    await db.exec(`
      create role fixture_reader;
      create type public.fixture_state as enum ('ready', 'done');
      create domain public.fixture_amount as numeric check (value >= 0);
      create table public.fixture_parent (id integer primary key);
      create table public.fixture_rounds (
        id bigint generated by default as identity primary key,
        parent_id integer references public.fixture_parent(id),
        amount public.fixture_amount not null default 1,
        state public.fixture_state not null default 'ready',
        secret text default '${marker}',
        computed numeric generated always as (amount * 2) stored,
        constraint fixture_positive check (amount > 0)
      );
      create index fixture_amount_idx on public.fixture_rounds ((amount + 1)) where state = 'ready';
      alter table public.fixture_rounds enable row level security;
      alter table public.fixture_rounds force row level security;
      create policy fixture_read on public.fixture_rounds for select to fixture_reader using (amount > 0);
      create policy fixture_insert on public.fixture_rounds as restrictive for insert to fixture_reader with check (amount < 100);
      grant usage on schema public to fixture_reader;
      grant select on public.fixture_rounds to fixture_reader;
      grant update (amount) on public.fixture_rounds to fixture_reader;
      grant usage on sequence public.fixture_rounds_id_seq to fixture_reader;
      alter default privileges in schema public grant select on tables to fixture_reader;
      create view public.fixture_view with (security_invoker = true) as select id, '${marker}'::text as safe_hash_only from public.fixture_rounds;
      grant select on public.fixture_view to fixture_reader;
      create materialized view public.fixture_materialized as select id from public.fixture_rounds;
      create function public.fixture_function(p_value integer default 1) returns text language sql security definer stable
        set search_path = public set "fixture.private" = '${marker}' as $$ select '${marker}'::text $$;
      revoke execute on function public.fixture_function(integer) from public;
      grant execute on function public.fixture_function(integer) to fixture_reader;
      create function public.fixture_trigger() returns trigger language plpgsql as $$ begin return new; end $$;
      create trigger fixture_update before update on public.fixture_rounds for each row when (old.amount is distinct from new.amount) execute function public.fixture_trigger('${marker}');
      create table public.fixture_partitioned (id integer, state text) partition by list (state);
      create table public.fixture_partition_ready partition of public.fixture_partitioned for values in ('ready');
      create table public.fixture_extension_table (id integer);
      create function public.fixture_extension_function() returns integer language sql as $$ select 1 $$;
      alter extension plpgsql add table public.fixture_extension_table;
      alter extension plpgsql add function public.fixture_extension_function();
    `);
    let baseline = await snapshot(db);
    await t.test('Repeated reads and a different search_path produce identical fingerprints', async () => {
      verifySnapshot(baseline);
      assert.deepEqual(await snapshot(db), baseline);
      await db.exec('begin; set local search_path = public, pg_catalog;');
      assert.deepEqual(await snapshot(db), baseline);
      await db.exec('rollback;');
    });
    await t.test('Table metadata covers columns, defaults, constraints, indexes, policies and grants', () => {
      const table = entry(baseline, 'relation', 'public.fixture_rounds');
      assert.equal(table.rls, true); assert.equal(table.force_rls, true);
      assert(table.acl.some(acl => acl.grantee === 'fixture_reader' && acl.privilege === 'SELECT'));
      assert.equal(entry(baseline, 'column', 'public.fixture_rounds.id').identity, 'd');
      assert.equal(entry(baseline, 'column', 'public.fixture_rounds.computed').generated, 's');
      assert.equal(entry(baseline, 'column', 'public.fixture_rounds.amount').not_null, true);
      assert(entry(baseline, 'column', 'public.fixture_rounds.amount').acl.some(acl => acl.grantee === 'fixture_reader' && acl.privilege === 'UPDATE'));
      assert.match(entry(baseline, 'column', 'public.fixture_rounds.secret').default_md5, /^[a-f0-9]{32}$/);
      assert.equal(entry(baseline, 'constraint', 'public.fixture_rounds.fixture_rounds_parent_id_fkey').referenced_relation, 'public.fixture_parent');
      const index = entry(baseline, 'index', 'public.fixture_amount_idx');
      assert.match(index.expression_md5, /^[a-f0-9]{32}$/); assert.match(index.predicate_md5, /^[a-f0-9]{32}$/);
      assert.deepEqual(entry(baseline, 'policy', 'public.fixture_rounds.fixture_read').roles, ['fixture_reader']);
      assert.match(entry(baseline, 'policy', 'public.fixture_rounds.fixture_insert').check_md5, /^[a-f0-9]{32}$/);
      assert.equal(entry(baseline, 'policy', 'public.fixture_rounds.fixture_insert').permissive, false);
      assert.equal(entry(baseline, 'sequence', 'public.fixture_rounds_id_seq').owned_by[0], 'public.fixture_rounds.id');
      assert.equal(entry(baseline, 'sequence', 'public.fixture_rounds_id_seq').maximum, '9223372036854775807', 'bigint limits survive JSON transport exactly');
      assert(entry(baseline, 'relation', 'public.fixture_rounds_id_seq').acl.some(acl => acl.grantee === 'fixture_reader' && acl.privilege === 'USAGE'));
      assert(baseline.entries.some(item => item.kind === 'default_acl' && item.metadata.acl.some(acl => acl.grantee === 'fixture_reader' && acl.privilege === 'SELECT')));
      assert.deepEqual(entry(baseline, 'type', 'public.fixture_state').enum_labels, ['ready', 'done']);
      assert.equal(entry(baseline, 'type', 'public.fixture_amount').base_type, 'numeric');
      assert.equal(entry(baseline, 'constraint', 'public.fixture_amount.fixture_amount_check').type, 'c');
    });
    await t.test('View options, routine security and trigger WHEN are captured without literal definitions', () => {
      assert.deepEqual(entry(baseline, 'relation', 'public.fixture_view').options, ['security_invoker=true']);
      assert.match(entry(baseline, 'relation', 'public.fixture_view').view_definition_md5, /^[a-f0-9]{32}$/);
      assert.equal(entry(baseline, 'relation', 'public.fixture_materialized').relation_kind, 'm');
      const routine = entry(baseline, 'routine', 'public.fixture_function(p_value integer)');
      assert.equal(routine.security_definer, true);
      assert.deepEqual(routine.configuration, ['search_path=public']);
      assert(routine.acl.some(acl => acl.grantee === 'fixture_reader' && acl.privilege === 'EXECUTE'));
      assert(!routine.acl.some(acl => acl.grantee === 'PUBLIC'));
      assert.equal(entry(baseline, 'trigger', 'public.fixture_rounds.fixture_update').when_present, true);
      assert.match(entry(baseline, 'trigger', 'public.fixture_rounds.fixture_update').arguments_md5, /^[a-f0-9]{32}$/);
      assert(!JSON.stringify(baseline).includes(marker), 'default, view, routine body, routine config and trigger argument literals are hashed');
    });
    await t.test('Extension-owned objects and internal foreign-key triggers are excluded', () => {
      assert(!baseline.entries.some(item => item.key.includes('fixture_extension_')));
      assert.deepEqual(baseline.entries.filter(item => item.kind === 'trigger').map(item => item.key), ['public.fixture_rounds.fixture_update']);
      assert.match(entry(baseline, 'relation', 'public.fixture_partitioned').partition_key_md5, /^[a-f0-9]{32}$/);
      assert.match(entry(baseline, 'relation', 'public.fixture_partition_ready').partition_bound_md5, /^[a-f0-9]{32}$/);
      assert.deepEqual(entry(baseline, 'relation', 'public.fixture_partition_ready').parents, ['public.fixture_partitioned']);
    });
    await t.test('Inserting customer rows and advancing sequences cannot change the schema fingerprint', async () => {
      await db.exec("insert into public.fixture_rounds(amount, secret) values (2, 'private_customer_row'); select nextval('public.fixture_rounds_id_seq');");
      assert.deepEqual(await snapshot(db), baseline);
      assert(!JSON.stringify(await snapshot(db)).includes('private_customer_row'));
    });
    await t.test('Physical column order does not change the semantic catalog fingerprint', async () => {
      await db.exec('create table public.fixture_reordered (left_value text, right_value numeric not null default 1);');
      const first = await snapshot(db);
      await db.exec('drop table public.fixture_reordered; create table public.fixture_reordered (right_value numeric not null default 1, left_value text);');
      assert.deepEqual(await snapshot(db), first, 'reconciliation can append missing columns without reproducing physical column positions');
      await db.exec('drop table public.fixture_reordered;');
      assert.deepEqual(await snapshot(db), baseline);
    });
    await t.test('Routine bodies, security settings and ACL changes alter their own hashes', async () => {
      const before = entry(baseline, 'routine', 'public.fixture_function(p_value integer)');
      await db.exec(`create or replace function public.fixture_function(p_value integer default 1) returns text language sql security definer stable set search_path = public set "fixture.private" = '${marker}' as $$ select 'changed_private_literal'::text $$;`);
      const changed = await snapshot(db);
      assert.notEqual(entry(changed, 'routine', 'public.fixture_function(p_value integer)').body_md5, before.body_md5);
      assert.notEqual(changed.schema_md5, baseline.schema_md5);
      await db.exec('alter function public.fixture_function(integer) security invoker; revoke execute on function public.fixture_function(integer) from fixture_reader;');
      const secured = await snapshot(db);
      assert.equal(entry(secured, 'routine', 'public.fixture_function(p_value integer)').security_definer, false);
      assert(!entry(secured, 'routine', 'public.fixture_function(p_value integer)').acl.some(acl => acl.grantee === 'fixture_reader'));
      verifySnapshot(secured); baseline = secured;
    });
    await t.test('RLS, policy, defaults and view definition changes are independently detected', async () => {
      await db.exec('alter table public.fixture_rounds no force row level security; alter policy fixture_read on public.fixture_rounds using (amount > 1); alter table public.fixture_rounds alter amount set default 3; create or replace view public.fixture_view with (security_invoker = true) as select id, secret as safe_hash_only from public.fixture_rounds;');
      const changed = await snapshot(db);
      assert.equal(entry(changed, 'relation', 'public.fixture_rounds').force_rls, false);
      assert.notEqual(entry(changed, 'policy', 'public.fixture_rounds.fixture_read').using_md5, entry(baseline, 'policy', 'public.fixture_rounds.fixture_read').using_md5);
      assert.notEqual(entry(changed, 'column', 'public.fixture_rounds.amount').default_md5, entry(baseline, 'column', 'public.fixture_rounds.amount').default_md5);
      assert.notEqual(entry(changed, 'relation', 'public.fixture_view').view_definition_md5, entry(baseline, 'relation', 'public.fixture_view').view_definition_md5);
      assert.notEqual(changed.schema_md5, baseline.schema_md5);
      verifySnapshot(changed);
    });
  } finally { await db.close(); }
});
