// Customer-flow regressions run the actual Sportsbook page with an isolated service.
// No fixture can reach a production service, customer account, or wallet.
const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '..');
let browser, server, base;
const clone = value => structuredClone(value);
const sdk = `export function createClient(){
 const unlocked=()=>{if(__fixture.authLock)throw Error('SDK called inside onAuthStateChange')};
 return {auth:{
  async getSession(){unlocked();const session=structuredClone(__fixture.session);if(__fixture.holdSession)await new Promise(r=>__fixture.sessionResolvers.push(r));return {data:{session},error:null}},
  onAuthStateChange(cb){__fixture.callbacks.push(cb);return {data:{subscription:{unsubscribe(){}}}}}
 },from(table){unlocked();let owner;const q={select(){return q},eq(k,v){if(k==='user_id')owner=v;return q},single(){unlocked();return __wallet({table,owner})}};return q},functions:{async invoke(name,{body}){unlocked();try{return {data:await __invoke({owner:__fixture.session?.user.id,name,body}),error:null}}catch(e){return {data:null,error:{message:e.message}}}}}};
}`;
function game(sport, index=0, live=false) {
 return {id:`event-${sport}-${index}`,commence_time:new Date(Date.now()+(live?-60000:3600000)).toISOString(),home_team:`${sport.toUpperCase()} Home ${index}`,away_team:`${sport.toUpperCase()} Away ${index}`,bookmakers:[{markets:[{key:'h2h',outcomes:[{name:`${sport.toUpperCase()} Home ${index}`,price:100},{name:`${sport.toUpperCase()} Away ${index}`,price:110}]},{key:'spreads',outcomes:[{name:`${sport.toUpperCase()} Home ${index}`,price:-110,point:-3.5}]}]}]};
}
test.before(async()=>{
 server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),headless:true,args:['--no-sandbox']});
});
test.after(async()=>{await browser?.close();await new Promise(r=>server.close(r))});
async function open(t, options={}) {
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});t.after(()=>context.close());
 const state={balances:{A:100,B:500},requests:new Map(),calls:[],walletCalls:[],heldWallets:[],heldInvokes:[],walletGate:new Set(),walletError:new Set(),...options};
 const commit=record=>{if(record.state==='accepted')return clone(record.receipt);state.balances[record.owner]-=record.payload.stake;record.state='accepted';record.receipt={ok:true,state:'accepted',request_id:record.payload.request_id,balance:state.balances[record.owner],wager:{id:'ticket-'+record.payload.request_id,stake:record.payload.stake,potential_return:record.payload.stake*2}};return clone(record.receipt)};
 await context.exposeBinding('__wallet',async(_source,{owner,table})=>{assert.equal(table,'wallets');state.walletCalls.push(owner);const data={balance:state.balances[owner]},error=state.walletError.has(owner)?{message:'Fixture wallet failure'}:null;if(state.walletGate.has(owner))await new Promise(r=>state.heldWallets.push({owner,resolve:r}));return {data,error}});
 await context.exposeBinding('__invoke',async(_source,call)=>{
  state.calls.push(clone(call));const {body,owner}=call,key=owner+'|'+body.request_id;assert.match(body.request_id,/^[0-9a-f-]{36}$/);
  if(body.recover){if(state.recoveryDown)throw Error('Fixture recovery unavailable');const r=state.requests.get(key);if(!r)return {ok:false,state:'not_found',request_id:body.request_id,retry_same_request:true};if(r.state==='accepted'||r.state==='rejected')return clone(r.receipt);return {ok:false,state:'pending',request_id:body.request_id,retry_same_request:true}}
  if(state.dropBeforeAccept){state.dropBeforeAccept=false;throw Error('Fixture connection lost before acceptance')}
  let record=state.requests.get(key);if(record){assert.deepEqual(body,record.payload,'retry must retain the immutable payload');if(record.state==='pending'&&state.resumeLease)return commit(record);return record.state==='accepted'||record.state==='rejected'?clone(record.receipt):{ok:false,state:'pending',request_id:body.request_id,retry_same_request:true}}
  record={owner,payload:clone(body),state:'pending'};state.requests.set(key,record);
  if(state.reject){record.state='rejected';record.receipt={ok:false,state:'rejected',request_id:body.request_id,error:'Fixture line changed',no_credits_charged:true};return clone(record.receipt)}
  if(state.holdInitial)await new Promise(r=>state.heldInvokes.push({record,resolve:r}));const response=commit(record);if(state.loseInitial){state.loseInitial=false;throw Error('Fixture response lost after acceptance')}return response;
 });
 await context.addInitScript(()=>{const session=id=>({user:{id,email:id+'@example.invalid'},access_token:'fixture-'+id});window.__fixture={session:session('A'),callbacks:[],authLock:false,holdSession:false,sessionResolvers:[],delays:{},gamesPrice:100};window.__session=session;window.__emit=s=>{__fixture.session=s;__fixture.authLock=true;try{for(const cb of __fixture.callbacks)cb(s?'SIGNED_IN':'SIGNED_OUT',s)}finally{__fixture.authLock=false}};window.__releaseSession=()=>{__fixture.holdSession=false;__fixture.sessionResolvers.splice(0).forEach(r=>r())}});
 await context.route('https://**/*',route=>route.abort());
 await context.route('https://cdn.jsdelivr.net/**',route=>route.fulfill({contentType:'text/javascript',body:sdk}));
 await context.route('https://qsvrvhcklnsbekxblpfo.supabase.co/**',async route=>{
  const body=route.request().postDataJSON();const f=await route.request().frame().evaluate(body=>({delay:__fixture.delays[body.mode+'|'+body.sport]||0,live:__fixture.live,price:__fixture.gamesPrice}),body);if(f.delay)await new Promise(r=>setTimeout(r,f.delay));let data;
  if(body.mode==='sports')data={sports:['nfl','nba','americanfootball_nfl','mma_mixed_martial_arts'].map(key=>({key,group:'Fixture',title:key,active:true}))};
  else if(body.mode==='games')data={games:[game(body.sport,0,f.live),game(body.sport,1,f.live)].map(g=>({...g,bookmakers:g.bookmakers.map(b=>({...b,markets:b.markets.map(m=>({...m,outcomes:m.outcomes.map(o=>({...o,price:f.price}))}))}))}))};
  else if(body.mode==='events')data={events:[game(body.sport)]};
  else if(body.mode==='prop_markets')data={prop_markets:['player_pass_yds','player_points']};
  else if(body.mode==='props')data={event:{...game(body.sport),bookmakers:[{markets:[{key:body.markets[0],outcomes:[{name:'Over',description:body.sport+' Player',point:250.5,price:-110}]}]}]}};
  else if(body.mode==='future_markets')data={futures:[{key:body.sport+'_winner',title:body.sport+' Winner'}]};
  else if(body.mode==='futures')data={future:{title:body.sport+' Winner'},futures:[{id:'future-'+body.sport,bookmakers:[{markets:[{key:'outrights',outcomes:[{name:body.sport+' Champion',price:500}]}]}]}]};
  else data={states:[]};
  try{await route.fulfill({contentType:'application/json',body:JSON.stringify(data)})}catch(e){if(!/closed|disposed/.test(e.message))throw e}
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/gameday-sportsbook.html');await page.locator('.odd').first().waitFor();
 t.after(()=>assert.deepEqual(errors,[],'no JS errors or Supabase auth-lock re-entry'));
 return {page,context,state,releaseWallet(owner){state.walletGate.delete(owner);state.heldWallets.filter(x=>x.owner===owner).forEach(x=>x.resolve());state.heldWallets=state.heldWallets.filter(x=>x.owner!==owner)},releaseInvoke(){state.holdInitial=false;state.heldInvokes.splice(0).forEach(x=>x.resolve())}};
}
async function prepare(p){await p.locator('.odd').first().click();await p.click('#openSlip');await p.fill('#stake','10')}
async function accepted(p){await p.locator('#slipMsg .success').waitFor()}
async function flush(p){await p.waitForTimeout(75)}
function countAccepted(s){return [...s.requests.values()].filter(x=>x.state==='accepted').length}

test('normal Single shows its accepted ticket, debit and cleared slip',async t=>{const {page:p,state:s}=await open(t);await prepare(p);await p.click('#place');await accepted(p);assert.equal(countAccepted(s),1);assert.equal(s.balances.A,90);assert.equal(await p.locator('#count').textContent(),'0');assert.match(await p.locator('#slipMsg').textContent(),/ticket-/);assert.equal(await p.locator('#balance').textContent(),'Balance: $90.00');assert.equal(await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('gameday.sportsbook.pending.')).length),0)});
test('Single rejects a second pick explicitly instead of silently discarding it',async t=>{const {page:p,state:s}=await open(t);await p.locator('.odd').nth(0).click();await p.locator('.odd').nth(2).click();assert.equal(await p.locator('#count').textContent(),'1');assert.match(await p.locator('#selectionNotice').textContent(),/Single wagers use one pick/);await p.click('#openSlip');await p.fill('#stake','10');await p.click('#place');await accepted(p);assert.equal(s.calls[0].body.selections.length,1);assert.equal(s.calls[0].body.selections[0].event_id,'event-nfl-0')});
test('different-event Parlay places both; changing it to Single preserves picks',async t=>{const {page:p,state:s}=await open(t);await p.click('#openSlip');await p.click('#parlay');await p.click('#closeSlip');await p.locator('.odd').nth(0).click();await p.locator('.odd').nth(2).click();await p.click('#openSlip');await p.click('#single');assert.equal(await p.locator('#count').textContent(),'2');assert(await p.locator('#parlay').evaluate(e=>e.classList.contains('active')));assert.match(await p.locator('#slipMsg').textContent(),/selections have been kept/);await p.fill('#stake','10');await p.click('#place');await accepted(p);assert.equal(s.calls[0].body.selections.length,2);assert.equal(s.calls[0].body.wager_type,'parlay')});
test('opposing or correlated same-event picks are blocked in Parlay',async t=>{const {page:p,state:s}=await open(t);await p.click('#openSlip');await p.click('#parlay');await p.click('#closeSlip');await p.locator('.odd').nth(0).click();await p.locator('.odd').nth(1).click();assert.equal(await p.locator('#count').textContent(),'1');assert.match(await p.locator('#selectionNotice').textContent(),/one selection from each event/);assert.equal(s.calls.length,0)});
test('pending placement locks type, amount, remove and duplicate Place',async t=>{const h=await open(t,{holdInitial:true}),{page:p,state:s}=h;await prepare(p);await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').disabled);for(const id of ['single','parlay','stake','place'])assert(await p.locator('#'+id).isDisabled());assert(await p.locator('[data-remove]').isDisabled());await p.evaluate(()=>{document.querySelector('#parlay').click();document.querySelector('#single').click();document.querySelector('#place').click();document.querySelector('[data-remove]').click()});assert.equal(s.calls.length,1);const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('gameday.sportsbook.pending.v1.A')));assert.equal(saved.payload.stake,10);assert.equal(saved.payload.wager_type,'single');h.releaseInvoke();await accepted(p);assert.equal(countAccepted(s),1);assert.equal(s.balances.A,90)});
test('lost accepted response recovers one exact ticket without another debit',async t=>{const {page:p,state:s}=await open(t,{loseInitial:true});await prepare(p);await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').textContent==='Check Wager');assert(await p.locator('#stake').isDisabled());await p.click('#place');await accepted(p);assert.equal(s.calls.filter(c=>!c.body.recover).length,1);assert.equal(s.calls.filter(c=>c.body.recover).length,1);assert.equal(countAccepted(s),1);assert.equal(s.balances.A,90);assert.equal(s.calls[0].body.request_id,s.calls[1].body.request_id)});
test('reload recovers committed response and receipt; no new wager is sent',async t=>{const {page:p,state:s}=await open(t,{loseInitial:true,recoveryDown:true});await prepare(p);await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').textContent==='Check Wager');const id=s.calls[0].body.request_id;s.recoveryDown=false;await p.reload();await accepted(p);assert.equal(s.calls.filter(c=>!c.body.recover).length,1);assert.equal(s.balances.A,90);assert.match(await p.locator('#slipMsg').textContent(),new RegExp('ticket-'+id));assert.equal(await p.locator('#count').textContent(),'0')});
test('request lost before acceptance resends the same UUID and frozen payload',async t=>{const {page:p,state:s}=await open(t,{dropBeforeAccept:true});await prepare(p);await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').textContent==='Check Wager');await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').textContent==='Retry This Wager');assert.equal(s.balances.A,100);assert(await p.locator('#stake').isDisabled());await p.click('#place');await accepted(p);const full=s.calls.filter(c=>!c.body.recover);assert.equal(full.length,2);assert.deepEqual(full[0].body,full[1].body);assert.equal(countAccepted(s),1);assert.equal(s.balances.A,90)});
test('definite rejection releases controls and a reviewed retry gets a new UUID',async t=>{const {page:p,state:s}=await open(t,{reject:true});await prepare(p);await p.click('#place');await p.waitForFunction(()=>document.querySelector('#slipMsg').textContent.includes('No credits were charged'));assert(await p.locator('#stake').isEnabled());assert(await p.locator('#parlay').isEnabled());assert.equal(s.balances.A,100);s.reject=false;await p.click('#place');await accepted(p);assert.notEqual(s.calls[0].body.request_id,s.calls[1].body.request_id);assert.equal(countAccepted(s),1)});
test('signout clears private slip and a late placement cannot repaint it',async t=>{const h=await open(t,{holdInitial:true}),{page:p,state:s}=h;await prepare(p);await p.click('#place');const snapshot=await p.evaluate(()=>{__emit(null);return {account:account.textContent,balance:balance.textContent,slip:slipItems.textContent,message:slipMsg.textContent,count:count.textContent}});assert.equal(snapshot.account,'Not signed in');assert.equal(snapshot.balance,'Balance: —');assert.equal(snapshot.count,'0');assert.equal(snapshot.message,'');assert(!snapshot.slip.includes('NFL Home'));h.releaseInvoke();await flush(p);assert.equal(await p.locator('#balance').textContent(),'Balance: —');assert.equal(await p.locator('#slipMsg').textContent(),'');assert.equal(countAccepted(s),1)});
test('account switch hides former pending ticket and ignores its late receipt',async t=>{const h=await open(t,{holdInitial:true}),{page:p}=h;await prepare(p);await p.click('#place');await p.evaluate(()=>__emit(__session('B')));await p.waitForFunction(()=>document.querySelector('#balance').textContent==='Balance: $500.00');h.releaseInvoke();await flush(p);assert.equal(await p.locator('#account').textContent(),'B@example.invalid');assert.equal(await p.locator('#balance').textContent(),'Balance: $500.00');assert.equal(await p.locator('#slipMsg').textContent(),'');assert.equal(await p.locator('#count').textContent(),'0')});
test('late wallet data and wallet failures cannot reuse the previous balance',async t=>{const h=await open(t),{page:p,state:s}=h;s.walletGate.add('A');await p.click('#refresh');await p.waitForTimeout(50);await p.evaluate(()=>__emit(__session('B')));await p.waitForFunction(()=>document.querySelector('#balance').textContent==='Balance: $500.00');h.releaseWallet('A');await flush(p);assert.equal(await p.locator('#slipBalance').textContent(),'$500.00');s.walletError.add('A');await p.evaluate(()=>__emit(__session('A')));await p.waitForFunction(()=>document.querySelector('#balance').textContent==='Balance unavailable');assert.equal(await p.locator('#slipBalance').textContent(),'—');assert(await p.locator('#place').isDisabled())});
test('stale getSession and back-to-back auth callbacks cannot restore A over B',async t=>{const {page:p}=await open(t);await p.evaluate(()=>{__fixture.holdSession=true});await p.click('#refresh');await p.waitForFunction(()=>__fixture.sessionResolvers.length===1);await p.evaluate(()=>{__emit(__session('A'));__emit(__session('B'))});await p.waitForFunction(()=>document.querySelector('#balance').textContent==='Balance: $500.00');await p.evaluate(()=>__releaseSession());await flush(p);assert.equal(await p.locator('#account').textContent(),'B@example.invalid');assert.equal(await p.locator('#balance').textContent(),'Balance: $500.00')});
test('late NFL odds cannot render or wager under an NBA selection',async t=>{const {page:p,state:s}=await open(t);await p.evaluate(()=>__fixture.delays['games|nfl']=400);await p.click('#refresh');await p.click('[data-sport="nba"]');await p.waitForFunction(()=>document.querySelector('#content').textContent.includes('NBA Home'));await p.waitForTimeout(500);assert.match(await p.locator('#content').textContent(),/NBA Home/);assert(!await p.locator('#content').textContent().then(v=>v.includes('NFL Home')));await prepare(p);await p.click('#place');await accepted(p);assert.equal(s.calls[0].body.selections[0].event_id,'event-nba-0');assert.equal(s.calls[0].body.selections[0].sport_key,'nba')});
test('late prop event or market cannot replace another sport or view',async t=>{const {page:p}=await open(t);await p.evaluate(()=>__fixture.delays['events|nfl']=400);await p.click('[data-view="props"]');await p.click('[data-sport="nba"]');await p.locator('[data-event]').waitFor();await p.waitForTimeout(500);assert.match(await p.locator('#content').textContent(),/NBA Home/);assert(!await p.locator('#content').textContent().then(v=>v.includes('NFL Home')));await p.evaluate(()=>__fixture.delays['prop_markets|nba']=400);await p.click('[data-event]');await p.click('[data-view="games"]');await p.locator('.odd').first().waitFor();await p.waitForTimeout(500);assert(await p.locator('.odd').first().isVisible());assert.equal(await p.locator('[data-prop]').count(),0)});
test('late future markets cannot replace the current Games board',async t=>{const {page:p}=await open(t);await p.evaluate(()=>__fixture.delays['future_markets|nfl']=400);await p.click('[data-view="futures"]');await p.click('[data-sport="nba"]');await p.click('[data-view="games"]');await p.locator('.odd').first().waitFor();await p.waitForTimeout(500);assert.match(await p.locator('#content').textContent(),/NBA Home/);assert.equal(await p.locator('[data-future]').count(),0)});
test('storage failure prevents any wager send rather than losing recovery identity',async t=>{const {page:p,state:s}=await open(t);await prepare(p);await p.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('Fixture storage blocked')}});await p.click('#place');assert.match(await p.locator('#slipMsg').textContent(),/storage blocked/);assert.equal(s.calls.length,0);assert.equal(s.balances.A,100)});

test('pending receipt survives reload and expired lease resumes only the same request',async t=>{
 const h=await open(t,{holdInitial:true}),{page:p,state:s}=h;await prepare(p);await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').disabled);
 const original=clone(s.calls[0].body);await p.reload();await p.waitForFunction(()=>document.querySelector('#place').textContent==='Check Wager'&&!document.querySelector('#place').disabled);
 assert(await p.locator('#stake').isDisabled());assert(await p.locator('#parlay').isDisabled());assert.equal(s.balances.A,100);
 await p.click('#place');await p.waitForFunction(()=>!document.querySelector('#place').disabled);assert.equal(s.balances.A,100);
 s.resumeLease=true;await p.click('#place');await accepted(p);h.releaseInvoke();await flush(p);
 const submits=s.calls.filter(x=>!x.body.recover);assert.equal(submits.length,3);for(const c of submits)assert.deepEqual(c.body,original);assert.equal(countAccepted(s),1);assert.equal(s.balances.A,90);
});
test('transport timeout keeps the frozen wager and recovers the late committed result',async t=>{
 const h=await open(t,{holdInitial:true}),{page:p,state:s}=h;await prepare(p);
 await p.evaluate(()=>{const original=window.setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms===15000?60:ms,...args)});
 await p.click('#place');await p.waitForFunction(()=>document.querySelector('#place').textContent==='Check Wager'&&!document.querySelector('#place').disabled);
 assert(await p.locator('#stake').isDisabled());await p.click('#place');await p.waitForFunction(()=>!document.querySelector('#place').disabled);
 h.releaseInvoke();await flush(p);await p.click('#place');await accepted(p);assert.equal(countAccepted(s),1);assert.equal(s.balances.A,90);
 assert(s.calls.every(c=>c.body.request_id===s.calls[0].body.request_id));
});
test('ungraded Worldwide sport is view-only before a customer can add a pick',async t=>{
 const {page:p,state:s}=await open(t);await p.selectOption('#sportSelect','mma_mixed_martial_arts');await p.locator('.odd').first().waitFor();
 assert(await p.locator('.odd').first().isDisabled());assert.equal(await p.locator('[data-sel]').count(),0);assert.match(await p.locator('#content').textContent(),/VIEW ONLY/);assert.equal(await p.locator('#count').textContent(),'0');assert.equal(s.calls.length,0);
});
test('Worldwide canonical NFL still permits its verified football props',async t=>{
 const {page:p,state:s}=await open(t);await p.selectOption('#sportSelect','americanfootball_nfl');await p.locator('.odd').first().waitFor();assert(await p.locator('.odd').first().isEnabled());
 await p.click('[data-view="props"]');await p.locator('[data-event]').click();await p.locator('[data-prop="player_pass_yds"]').click();await p.locator('.odd').first().click();await p.click('#openSlip');await p.fill('#stake','10');await p.click('#place');await accepted(p);
 assert.equal(s.calls[0].body.selections[0].sport_key,'americanfootball_nfl');assert.equal(s.calls[0].body.selections[0].market_key,'player_pass_yds');
});
test('browser capabilities match the service score-coverage contract',()=>{
 const vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');const html=fs.readFileSync(path.join(root,'gameday-sportsbook.html'),'utf8');
 const client=html.slice(html.indexOf('const GRADING_ALIASES'),html.indexOf('const SPORT_LABELS'));
 const backend=stripTypeScriptTypes(fs.readFileSync(path.join(root,'supabase/functions/place-test-wager/sport-keys.ts'),'utf8')).replaceAll('export function','function');
 const a=vm.runInNewContext(client+';({aliases:GRADING_ALIASES,keys:[...GRADED_SPORTS]})'),b=vm.runInNewContext(backend+';({aliases:ALIASES,keys:[...GRADED_SPORTS]})');
 assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));
});
