import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Content-Type': 'application/json',
}
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: corsHeaders }) }
function clean(v: unknown) { return String(v ?? '').trim() }
function normalizeName(v: unknown) { return clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\b(fc|cf|sc|club|team)\b/g,' ').replace(/\s+/g,' ').trim() }
function isoDate(offsetDays=0){const d=new Date(Date.now()+offsetDays*86400000);return d.toISOString().slice(0,10)}
function serviceKey(){const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(legacy)return legacy;const raw=Deno.env.get('SUPABASE_SECRET_KEYS');if(!raw)return null;try{const parsed=JSON.parse(raw);return parsed.default??Object.values(parsed)[0]??null}catch{return null}}
async function getApi(url:string,key:string){const r=await fetch(url,{headers:{'x-apisports-key':key}});const raw=await r.text();let data:any;try{data=raw?JSON.parse(raw):null}catch{data={errors:{parse:raw}}}if(!r.ok)throw new Error(`API-SPORTS ${r.status}`);if(data?.errors&&((Array.isArray(data.errors)&&data.errors.length)||(!Array.isArray(data.errors)&&Object.keys(data.errors).length)))throw new Error(`API-SPORTS: ${JSON.stringify(data.errors)}`);return Array.isArray(data?.response)?data.response:[]}
async function getJson(url:string){const r=await fetch(url,{headers:{'Accept':'application/json','User-Agent':'GameDay-Sports/1.0'}});if(!r.ok)throw new Error(`MLB ${r.status}`);return await r.json()}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null}
function scoreTotal(obj:any){if(obj==null)return null;if(typeof obj==='number')return obj;if(typeof obj==='string'&&obj.trim()!=='')return num(obj);if(typeof obj==='object'){for(const k of ['total','points','runs','goals']){const n=num(obj?.[k]);if(n!==null)return n}}return null}
function ordinal(n:number){const mod100=n%100;if(mod100>=11&&mod100<=13)return `${n}th`;switch(n%10){case 1:return `${n}st`;case 2:return `${n}nd`;case 3:return `${n}rd`;default:return `${n}th`}}
function baseballPeriod(item:any,short:string,long:string){const m=short.match(/^IN(\d+)$/i);if(!m)return short&&!['NS','FT'].includes(short)?short:(long||null);const inning=Number(m[1]);const homeInnings=item?.scores?.home?.innings??item?.score?.home?.innings??{};const homeValue=homeInnings?.[inning]??homeInnings?.[String(inning)];const half=(homeValue===null||homeValue===undefined||homeValue==='')?'Top':'Bot';return `${half} ${ordinal(inning)}`}
function mapGridGame(item:any,sport:string){const game=item?.game??item,status=game?.status??item?.status??{},home=item?.teams?.home??item?.home??{},away=item?.teams?.away??item?.away??{},short=clean(status?.short),long=clean(status?.long),timer=clean(status?.timer??game?.timer??item?.timer),finished=['FT','AOT','AP','CANC','PST'].includes(short),notStarted=['NS','TBD'].includes(short);const period=(sport==='mlb'||sport==='baseball')?baseballPeriod(item,short,long):(short&&!['NS','FT'].includes(short)?short:(long&&!finished&&!notStarted?long:null));return{provider:'api-sports',sport,provider_event_id:clean(game?.id??item?.id),home_team:clean(home?.name),away_team:clean(away?.name),home_key:normalizeName(home?.name),away_key:normalizeName(away?.name),home_score:scoreTotal(item?.scores?.home??item?.score?.home),away_score:scoreTotal(item?.scores?.away??item?.score?.away),period,clock:timer||null,status_short:short||null,status_long:long||null,live:!finished&&!notStarted,completed:finished}}
function mapSoccer(item:any){const fixture=item?.fixture??{},status=fixture?.status??{},home=item?.teams?.home??{},away=item?.teams?.away??{},elapsed=num(status?.elapsed),seconds=clean(status?.seconds),short=clean(status?.short),finished=['FT','AET','PEN','CANC','PST'].includes(short),notStarted=['NS','TBD'].includes(short);return{provider:'api-sports',sport:'soccer',provider_event_id:clean(fixture?.id),home_team:clean(home?.name),away_team:clean(away?.name),home_key:normalizeName(home?.name),away_key:normalizeName(away?.name),home_score:num(item?.goals?.home),away_score:num(item?.goals?.away),period:clean(status?.long)||short||null,clock:seconds||(elapsed!==null?`${elapsed}'`:null),status_short:short||null,status_long:clean(status?.long)||null,live:!finished&&!notStarted,completed:finished}}
async function fetchOneDate(host:string,sport:string,key:string,offset=0){const rows=await getApi(`https://${host}/games?date=${isoDate(offset)}`,key);return rows.map((x:any)=>mapGridGame(x,sport)).filter((x:any)=>x.live)}
async function fetchDateGames(host:string,sport:string,key:string){let rows=await fetchOneDate(host,sport,key,0);if(!rows.length)rows=await fetchOneDate(host,sport,key,-1).catch(()=>[]);return rows}
async function mlbScheduleGames(){const all:any[]=[];for(const offset of [0,-1]){try{const d=await getJson(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${isoDate(offset)}`);for(const day of d?.dates??[])for(const g of day?.games??[])all.push(g)}catch(e){console.error('MLB schedule lookup failed:',e instanceof Error?e.message:String(e))}}return all}
async function enrichMlb(states:any[]){if(!states.length)return states;const schedule=await mlbScheduleGames();const byMatch=new Map<string,any>();for(const g of schedule){const home=normalizeName(g?.teams?.home?.team?.name),away=normalizeName(g?.teams?.away?.team?.name);if(home&&away)byMatch.set(`${away}|${home}`,g)}return await Promise.all(states.map(async(state:any)=>{const g=byMatch.get(`${state.away_key}|${state.home_key}`);if(!g?.gamePk)return{...state,clock:null};try{const ls=await getJson(`https://statsapi.mlb.com/api/v1/game/${g.gamePk}/linescore`);const inningState=clean(ls?.inningState),inningOrdinal=clean(ls?.currentInningOrdinal)||(num(ls?.currentInning)!==null?ordinal(Number(ls.currentInning)):'');const half=inningState.toLowerCase().startsWith('bottom')?'Bot':inningState.toLowerCase().startsWith('top')?'Top':inningState;const offense=ls?.offense??{};const balls=num(ls?.balls),strikes=num(ls?.strikes),outs=num(ls?.outs),bases={first:Boolean(offense?.first),second:Boolean(offense?.second),third:Boolean(offense?.third)};return{...state,provider:'api-sports+mlb',period:(half&&inningOrdinal)?`${half} ${inningOrdinal}`:state.period,clock:null,balls,strikes,outs,bases,batter:clean(offense?.batter?.fullName)||null,on_deck:clean(offense?.onDeck?.fullName)||null,game_pk:String(g.gamePk)}}catch(e){console.error('MLB live detail failed:',e instanceof Error?e.message:String(e));return{...state,clock:null}}}))}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders});if(req.method!=='GET'&&req.method!=='POST')return json({error:'Method not allowed'},405);const key=Deno.env.get('API_SPORTS_KEY');if(!key)return json({error:'API_SPORTS_KEY is not configured'},503);let body:any={};if(req.method==='POST'){try{body=await req.json()}catch{body={}}}const requestUrl=new URL(req.url),sport=clean(requestUrl.searchParams.get('sport')??body?.sport).toLowerCase();if(!sport)return json({error:'sport is required'},400);
const supabaseUrl=Deno.env.get('SUPABASE_URL'),svc=serviceKey(),cacheKey=`live-state:${sport}`;let admin:any=null,stalePayload:any=null;if(supabaseUrl&&svc){admin=createClient(supabaseUrl,svc,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});try{const{data}=await admin.from('odds_response_cache').select('payload,expires_at').eq('cache_key',cacheKey).maybeSingle();if(data?.payload){stalePayload=data.payload;if(new Date(data.expires_at).getTime()>Date.now())return json(data.payload)}}catch(e){console.error('Live-state cache read failed:',e instanceof Error?e.message:String(e))}}
try{let states:any[]=[];if(['nfl','ncaaf'].includes(sport))states=await fetchDateGames('v1.american-football.api-sports.io',sport,key);else if(['nba','wnba','ncaab','basketball'].includes(sport))states=await fetchDateGames('v1.basketball.api-sports.io',sport,key);else if(['mlb','baseball'].includes(sport)){states=await fetchDateGames('v1.baseball.api-sports.io',sport,key);states=await enrichMlb(states)}else if(['nhl','hockey'].includes(sport))states=await fetchDateGames('v1.hockey.api-sports.io',sport,key);else if(['mls','epl','ucl','soccer','football'].includes(sport)){const rows=await getApi('https://v3.football.api-sports.io/fixtures?live=all',key);states=rows.map(mapSoccer).filter((x:any)=>x.live)}else return json({error:'Live state is not configured for this sport yet'},400);const ttlMs=states.length?15000:300000,payload={provider:'api-sports',sport,count:states.length,states,fetched_at:new Date().toISOString(),cache_ttl_seconds:ttlMs/1000};if(admin){try{const now=new Date();await admin.from('odds_response_cache').upsert({cache_key:cacheKey,payload,expires_at:new Date(now.getTime()+ttlMs).toISOString(),updated_at:now.toISOString()},{onConflict:'cache_key'})}catch(e){console.error('Live-state cache write failed:',e instanceof Error?e.message:String(e))}}return json(payload)}catch(e){console.error('GameDay live-state failed:',e instanceof Error?e.message:String(e));if(stalePayload){const cachedStates=(stalePayload.states||[]).map((s:any)=>({...s,period:s?.period?`${s.period} • Cached`:'Live • Cached'}));return json({...stalePayload,states:cachedStates,stale:true,warning:'Live game state is temporarily using cached data.'})}return json({error:'Unable to load live game state'},502)}})
