// Both placement and grading use the same canonical keys. Scores coverage was
// verified against https://the-odds-api.com/sports-odds-data/sports-apis.html
// on 2026-10-10. Other sport families/futures remain view-only until their
// grading semantics are verified; provider availability alone is insufficient.
const ALIASES: Record<string, string> = {
  nfl: 'americanfootball_nfl', football: 'americanfootball_nfl',
  ncaaf: 'americanfootball_ncaaf', nba: 'basketball_nba', basketball: 'basketball_nba',
  wnba: 'basketball_wnba', ncaab: 'basketball_ncaab',
  mlb: 'baseball_mlb', baseball: 'baseball_mlb',
  nhl: 'icehockey_nhl', hockey: 'icehockey_nhl',
  mls: 'soccer_usa_mls', epl: 'soccer_epl', ucl: 'soccer_uefa_champs_league',
};
const GRADED_SPORTS = new Set([
  'americanfootball_cfl',
  'americanfootball_ncaaf',
  'americanfootball_ncaaf_fcs',
  'americanfootball_nfl',
  'americanfootball_nfl_preseason',
  'americanfootball_ufl',
  'baseball_mlb',
  'baseball_mlb_preseason',
  'basketball_euroleague',
  'basketball_nba',
  'basketball_nba_preseason',
  'basketball_nba_summer_league',
  'basketball_wnba',
  'basketball_ncaab',
  'basketball_wncaab',
  'basketball_nbl',
  'icehockey_nhl',
  'icehockey_nhl_preseason',
  'icehockey_sweden_hockey_league',
  'icehockey_sweden_allsvenskan',
  'soccer_argentina_primera_division',
  'soccer_australia_aleague',
  'soccer_austria_bundesliga',
  'soccer_belgium_first_div',
  'soccer_brazil_campeonato',
  'soccer_brazil_serie_b',
  'soccer_chile_campeonato',
  'soccer_china_superleague',
  'soccer_denmark_superliga',
  'soccer_efl_champ',
  'soccer_england_efl_cup',
  'soccer_england_league1',
  'soccer_england_league2',
  'soccer_epl',
  'soccer_fa_cup',
  'soccer_fifa_world_cup',
  'soccer_fifa_world_cup_qualifiers_europe',
  'soccer_fifa_world_cup_qualifiers_south_america',
  'soccer_fifa_world_cup_womens',
  'soccer_fifa_club_world_cup',
  'soccer_finland_veikkausliiga',
  'soccer_france_coupe_de_france',
  'soccer_france_ligue_one',
  'soccer_france_ligue_two',
  'soccer_germany_bundesliga',
  'soccer_germany_bundesliga2',
  'soccer_germany_bundesliga_women',
  'soccer_germany_dfb_pokal',
  'soccer_germany_liga3',
  'soccer_greece_super_league',
  'soccer_italy_coppa_italia',
  'soccer_italy_serie_a',
  'soccer_italy_serie_b',
  'soccer_japan_j_league',
  'soccer_korea_kleague1',
  'soccer_league_of_ireland',
  'soccer_mexico_ligamx',
  'soccer_netherlands_eredivisie',
  'soccer_norway_eliteserien',
  'soccer_poland_ekstraklasa',
  'soccer_portugal_primeira_liga',
  'soccer_russia_premier_league',
  'soccer_spain_copa_del_rey',
  'soccer_spain_la_liga',
  'soccer_spain_segunda_division',
  'soccer_saudi_arabia_pro_league',
  'soccer_spl',
  'soccer_sweden_allsvenskan',
  'soccer_sweden_superettan',
  'soccer_switzerland_superleague',
  'soccer_turkey_super_league',
  'soccer_uefa_europa_conference_league',
  'soccer_uefa_champs_league',
  'soccer_uefa_champs_league_qualification',
  'soccer_uefa_champs_league_women',
  'soccer_uefa_europa_league',
  'soccer_uefa_european_championship',
  'soccer_uefa_euro_qualification',
  'soccer_uefa_nations_league',
  'soccer_concacaf_leagues_cup',
  'soccer_conmebol_copa_america',
  'soccer_conmebol_copa_libertadores',
  'soccer_conmebol_copa_sudamericana',
  'soccer_usa_mls',
]);
export function resolveGradingSport(value: unknown): string | null {
  const key = String(value ?? '').trim().toLowerCase();
  const canonical = ALIASES[key] ?? key;
  return GRADED_SPORTS.has(canonical) ? canonical : null;
}
export function isFootballGradingSport(value: unknown): boolean {
  return ['americanfootball_nfl', 'americanfootball_ncaaf'].includes(resolveGradingSport(value) ?? '');
}
export function isMlbGradingSport(value: unknown): boolean {
  return resolveGradingSport(value) === 'baseball_mlb';
}
