create table if not exists public.sports_events (
  id uuid primary key default gen_random_uuid(),
  provider_event_id text not null unique,
  sport_key text not null,
  sport_title text,
  commence_time timestamptz not null,
  home_team text,
  away_team text,
  status text not null default 'scheduled' check (status in ('scheduled','live','finished','cancelled','postponed')),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sports_markets (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.sports_events(id) on delete cascade,
  provider_market_key text not null,
  market_title text,
  market_type text not null default 'game' check (market_type in ('game','prop','future')),
  status text not null default 'open' check (status in ('open','suspended','closed')),
  line_method text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, provider_market_key)
);

create table if not exists public.sports_outcomes (
  id uuid primary key default gen_random_uuid(),
  market_id uuid not null references public.sports_markets(id) on delete cascade,
  outcome_name text not null,
  description text,
  point numeric,
  american_odds integer not null,
  source_book_count integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists sports_outcomes_identity_idx
  on public.sports_outcomes (market_id, outcome_name, coalesce(description, ''));

create table if not exists public.sports_line_history (
  id bigint generated by default as identity primary key,
  outcome_id uuid not null references public.sports_outcomes(id) on delete cascade,
  point numeric,
  american_odds integer not null,
  source_book_count integer,
  captured_at timestamptz not null default now()
);

create table if not exists public.sports_provider_snapshots (
  id bigint generated by default as identity primary key,
  provider text not null,
  mode text not null,
  sport_key text,
  provider_event_id text,
  payload jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists sports_events_sport_time_idx
  on public.sports_events (sport_key, commence_time);
create index if not exists sports_events_status_idx
  on public.sports_events (status, commence_time);
create index if not exists sports_markets_event_idx
  on public.sports_markets (event_id);
create index if not exists sports_markets_type_status_idx
  on public.sports_markets (market_type, status);
create index if not exists sports_outcomes_market_idx
  on public.sports_outcomes (market_id);
create index if not exists sports_line_history_outcome_time_idx
  on public.sports_line_history (outcome_id, captured_at desc);
create index if not exists sports_provider_snapshots_lookup_idx
  on public.sports_provider_snapshots (provider, mode, sport_key, captured_at desc);

alter table public.sports_events enable row level security;
alter table public.sports_markets enable row level security;
alter table public.sports_outcomes enable row level security;
alter table public.sports_line_history enable row level security;
alter table public.sports_provider_snapshots enable row level security;

revoke all on table public.sports_events from anon, authenticated;
revoke all on table public.sports_markets from anon, authenticated;
revoke all on table public.sports_outcomes from anon, authenticated;
revoke all on table public.sports_line_history from anon, authenticated;
revoke all on table public.sports_provider_snapshots from anon, authenticated;

grant select, insert, update, delete on table public.sports_events to service_role;
grant select, insert, update, delete on table public.sports_markets to service_role;
grant select, insert, update, delete on table public.sports_outcomes to service_role;
grant select, insert, update, delete on table public.sports_line_history to service_role;
grant select, insert, update, delete on table public.sports_provider_snapshots to service_role;
grant usage, select on all sequences in schema public to service_role;
